fieldtrip_dir = getenv('FIELDTRIP_DIR');
results_dir   = getenv('STERN_RESULTS_DIR');

erp_mat_file = fullfile( ...
    results_dir, ...
    'mat', ...
    'stern_all_channel_subject_erp.mat');

assert(isfile(fullfile(fieldtrip_dir, 'ft_defaults.m')), ...
    'FieldTrip not found: %s', fieldtrip_dir);
assert(isfile(erp_mat_file), ...
    'ERP MAT file not found: %s', erp_mat_file);

figure_dir  = fullfile(results_dir, 'figures');
table_dir   = fullfile(results_dir, 'tables');
summary_dir = fullfile(results_dir, 'summaries');
mat_dir     = fullfile(results_dir, 'mat');

if ~isfolder(figure_dir), mkdir(figure_dir); end
if ~isfolder(table_dir), mkdir(table_dir); end
if ~isfolder(summary_dir), mkdir(summary_dir); end
if ~isfolder(mat_dir), mkdir(mat_dir); end

addpath(fieldtrip_dir);
ft_defaults;

loaded = load(erp_mat_file);

erp_uv       = loaded.erp_uv;
times_ms     = double(loaded.times_ms(:)');
scalp_labels = loaded.scalp_labels;
conditions   = loaded.conditions;
subjects     = loaded.subjects;
chanlocs     = loaded.chanlocs;

n_conditions = size(erp_uv, 1);
n_subjects   = size(erp_uv, 2);
n_channels   = size(erp_uv, 3);
n_times      = size(erp_uv, 4);

assert(n_conditions == 3, ...
    'Expected 3 conditions, found %d.', n_conditions);
assert(n_subjects == 13, ...
    'Expected 13 subjects, found %d.', n_subjects);
assert(n_channels == 69, ...
    'Expected 69 scalp channels, found %d.', n_channels);
assert(n_times == numel(times_ms), ...
    'Time dimension does not match times_ms.');
assert(sum(isnan(erp_uv), 'all') == 0, ...
    'ERP array contains NaN values.');

scalp_labels = cellstr(string(scalp_labels));
conditions   = cellstr(string(conditions));
subjects     = cellstr(string(subjects));

fprintf('\n=== BUILDING FIELDTRIP DATA STRUCTURES ===\n');

coords = [ ...
    [chanlocs.X]' ...
    [chanlocs.Y]' ...
    [chanlocs.Z]'];

assert(isequal(size(coords), [n_channels 3]), ...
    'Unexpected electrode-coordinate matrix size: %s', ...
    mat2str(size(coords)));
assert(all(isfinite(coords), 'all'), ...
    'Electrode coordinates contain non-finite values.');

elec = [];
elec.label   = scalp_labels(:);
elec.chanpos = coords;
elec.elecpos = coords;
elec.unit    = 'arbitrary';

condition_data = cell(1, n_conditions);

for c = 1:n_conditions
    condition_data{c} = cell(1, n_subjects);

    for s = 1:n_subjects
        data = [];
        data.label  = scalp_labels(:);
        data.time   = times_ms ./ 1000;
        data.avg    = squeeze(erp_uv(c, s, :, :));
        data.dimord = 'chan_time';
        data.elec   = elec;
        data.fsample = 125;
        condition_data{c}{s} = data;
    end
end

fprintf('\n=== BUILDING SYMMETRIC CHANNEL NEIGHBOURS ===\n');

k_nearest = 4;
distance_matrix = nan(n_channels, n_channels);

for i = 1:n_channels
    for j = 1:n_channels
        distance_matrix(i, j) = norm(coords(i, :) - coords(j, :));
    end
end

adjacency = false(n_channels, n_channels);

for i = 1:n_channels
    distances = distance_matrix(i, :);
    distances(i) = inf;

    [~, order] = sort(distances, 'ascend');
    selected = order(1:k_nearest);
    adjacency(i, selected) = true;
end

adjacency = adjacency | adjacency';
adjacency(1:n_channels+1:end) = false;

neighbours = repmat( ...
    struct('label', '', 'neighblabel', {{}}), ...
    n_channels, ...
    1);

for i = 1:n_channels
    neighbours(i).label = scalp_labels{i};
    neighbours(i).neighblabel = ...
        scalp_labels(find(adjacency(i, :)));
end

neighbour_degree = sum(adjacency, 2);

assert(min(neighbour_degree) >= 4, ...
    'A channel has fewer than four neighbours.');

neighbour_table_file = fullfile( ...
    table_dir, ...
    'stern_channel_neighbours.tsv');

channel_column = string(scalp_labels(:));
degree_column = neighbour_degree;
neighbour_column = strings(n_channels, 1);

for i = 1:n_channels
    neighbour_column(i) = strjoin( ...
        string(neighbours(i).neighblabel), ...
        ',');
end

neighbour_table = table( ...
    channel_column, ...
    degree_column, ...
    neighbour_column, ...
    'VariableNames', { ...
        'channel', ...
        'degree', ...
        'neighbours'});

writetable( ...
    neighbour_table, ...
    neighbour_table_file, ...
    'FileType', 'text', ...
    'Delimiter', '\t');

neighbour_mat_file = fullfile( ...
    mat_dir, ...
    'stern_channel_neighbours.mat');

save( ...
    neighbour_mat_file, ...
    'neighbours', ...
    'adjacency', ...
    'coords', ...
    'scalp_labels');

fprintf('NEIGHBOUR_DEGREE_MIN=%d\n', min(neighbour_degree));
fprintf('NEIGHBOUR_DEGREE_MEDIAN=%.1f\n', median(neighbour_degree));
fprintf('NEIGHBOUR_DEGREE_MAX=%d\n', max(neighbour_degree));

contrast_names = { ...
    'Memorize_minus_Ignore', ...
    'Probe_minus_Memorize', ...
    'Probe_minus_Ignore'};

contrast_pretty = { ...
    'Memorize − Ignore', ...
    'Probe − Memorize', ...
    'Probe − Ignore'};

contrast_pairs = [ ...
    2 1; ...
    3 2; ...
    3 1];

stats = cell(1, size(contrast_pairs, 1));

all_contrast = strings(0, 1);
all_sign = strings(0, 1);
all_cluster_index = [];
all_pvalue = [];
all_clusterstat = [];
all_significant = [];
all_time_start_ms = [];
all_time_end_ms = [];
all_n_channel_time_samples = [];
all_n_channels = [];
all_channels = strings(0, 1);
all_peak_t = [];
all_peak_channel = strings(0, 1);
all_peak_time_ms = [];

fprintf('\n=== RUNNING EXACT CLUSTER-BASED PERMUTATION TESTS ===\n');
fprintf('STATFUN_COMPUTEPROB=default_no; corrected probabilities from Monte Carlo layer\n');

for k = 1:size(contrast_pairs, 1)
    condition_a = contrast_pairs(k, 1);
    condition_b = contrast_pairs(k, 2);

    cfg = [];
    cfg.channel          = 'all';
    cfg.latency          = [0 1];
    cfg.parameter        = 'avg';
    cfg.method           = 'montecarlo';
    cfg.statistic        = 'ft_statfun_depsamplesT';
    cfg.correctm         = 'cluster';
    cfg.clusteralpha     = 0.05;
    cfg.clusterstatistic = 'maxsum';
    cfg.minnbchan        = 2;
    cfg.neighbours       = neighbours;
    cfg.tail             = 0;
    cfg.clustertail      = 0;
    cfg.alpha            = 0.05;
    cfg.correcttail      = 'alpha';
    cfg.numrandomization = 'all';

    design = zeros(2, 2 * n_subjects);
    design(1, :) = [1:n_subjects 1:n_subjects];
    design(2, :) = [ ...
        ones(1, n_subjects) ...
        2 .* ones(1, n_subjects)];

    cfg.design = design;
    cfg.uvar   = 1;
    cfg.ivar   = 2;

    inputs = [ ...
        condition_data{condition_a} ...
        condition_data{condition_b}];

    fprintf('\n--- %s ---\n', contrast_pretty{k});

    stat = ft_timelockstatistics(cfg, inputs{:});
    stats{k} = stat;

    stat_file = fullfile( ...
        mat_dir, ...
        ['stern_erp_cluster_' contrast_names{k} '.mat']);

    save(stat_file, 'stat', '-v7.3');

    [rows, description] = summarize_clusters( ...
        stat, ...
        contrast_names{k}, ...
        0.05);

    fprintf('%s\n', description);

    if ~isempty(rows.contrast)
        all_contrast = [all_contrast; rows.contrast]; %#ok<AGROW>
        all_sign = [all_sign; rows.sign]; %#ok<AGROW>
        all_cluster_index = [all_cluster_index; rows.cluster_index]; %#ok<AGROW>
        all_pvalue = [all_pvalue; rows.pvalue]; %#ok<AGROW>
        all_clusterstat = [all_clusterstat; rows.clusterstat]; %#ok<AGROW>
        all_significant = [all_significant; rows.significant]; %#ok<AGROW>
        all_time_start_ms = [all_time_start_ms; rows.time_start_ms]; %#ok<AGROW>
        all_time_end_ms = [all_time_end_ms; rows.time_end_ms]; %#ok<AGROW>
        all_n_channel_time_samples = [ ...
            all_n_channel_time_samples; ...
            rows.n_channel_time_samples]; %#ok<AGROW>
        all_n_channels = [all_n_channels; rows.n_channels]; %#ok<AGROW>
        all_channels = [all_channels; rows.channels]; %#ok<AGROW>
        all_peak_t = [all_peak_t; rows.peak_t]; %#ok<AGROW>
        all_peak_channel = [all_peak_channel; rows.peak_channel]; %#ok<AGROW>
        all_peak_time_ms = [all_peak_time_ms; rows.peak_time_ms]; %#ok<AGROW>
    end
end

cluster_table = table( ...
    all_contrast, ...
    all_sign, ...
    all_cluster_index, ...
    all_pvalue, ...
    all_clusterstat, ...
    logical(all_significant), ...
    all_time_start_ms, ...
    all_time_end_ms, ...
    all_n_channel_time_samples, ...
    all_n_channels, ...
    all_channels, ...
    all_peak_t, ...
    all_peak_channel, ...
    all_peak_time_ms, ...
    'VariableNames', { ...
        'contrast', ...
        'sign', ...
        'cluster_index', ...
        'pvalue', ...
        'cluster_statistic', ...
        'significant_p_lt_0_05', ...
        'time_start_ms', ...
        'time_end_ms', ...
        'n_channel_time_samples', ...
        'n_channels', ...
        'channels', ...
        'peak_t', ...
        'peak_channel', ...
        'peak_time_ms'});

cluster_table_file = fullfile( ...
    table_dir, ...
    'stern_erp_cluster_results.tsv');

writetable( ...
    cluster_table, ...
    cluster_table_file, ...
    'FileType', 'text', ...
    'Delimiter', '\t');

fprintf('\n=== CREATING NEIGHBOUR DIAGNOSTIC FIGURE ===\n');

neighbour_figure = fullfile( ...
    figure_dir, ...
    'stern_channel_neighbours.png');

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1100 900]);

hold on;

for i = 1:n_channels
    for j = i+1:n_channels
        if adjacency(i, j)
            plot( ...
                [coords(i, 1) coords(j, 1)], ...
                [coords(i, 2) coords(j, 2)], ...
                '-', ...
                'LineWidth', 0.5, ...
                'HandleVisibility', 'off');
        end
    end
end

scatter(coords(:, 1), coords(:, 2), 35, 'filled');

for i = 1:n_channels
    text( ...
        coords(i, 1), ...
        coords(i, 2), ...
        [' ' scalp_labels{i}], ...
        'FontSize', 7);
end

axis equal;
axis off;
title(sprintf( ...
    'STERN symmetric %d-nearest EEG neighbour graph', ...
    k_nearest));

exportgraphics(fig, neighbour_figure, 'Resolution', 300);
close(fig);

fprintf('\n=== CREATING CLUSTER T-MAP FIGURE ===\n');

tmap_figure = fullfile( ...
    figure_dir, ...
    'stern_erp_cluster_tmaps.png');

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1550 1150]);

tiledlayout(3, 1, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

for k = 1:numel(stats)
    stat = stats{k};

    nexttile;
    imagesc( ...
        stat.time .* 1000, ...
        1:numel(stat.label), ...
        stat.stat);

    set(gca, 'YDir', 'normal');
    hold on;

    if isfield(stat, 'mask') && any(stat.mask, 'all')
        contour( ...
            stat.time .* 1000, ...
            1:numel(stat.label), ...
            double(stat.mask), ...
            [0.5 0.5], ...
            'k', ...
            'LineWidth', 1.2);
    end

    symmetric_limit = max(abs(stat.stat), [], 'all');
    if symmetric_limit == 0
        symmetric_limit = 1;
    end
    clim([-symmetric_limit symmetric_limit]);

    ylabel('EEG channel');
    xlabel('Time (ms)');
    title(contrast_pretty{k});
    colorbar;

    tick_indices = 1:5:numel(stat.label);
    yticks(tick_indices);
    yticklabels(stat.label(tick_indices));
end

sgtitle( ...
    ['STERN paired channel × time cluster tests ' ...
     '(black outline: corrected p < 0.05)']);

exportgraphics(fig, tmap_figure, 'Resolution', 300);
close(fig);

fprintf('\n=== CREATING REPRESENTATIVE WAVEFORM FIGURE ===\n');

waveform_figure = fullfile( ...
    figure_dir, ...
    'stern_erp_cluster_representative_waveforms.png');

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1550 1050]);

tiledlayout(3, 1, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

line_colors = lines(2);

for k = 1:numel(stats)
    stat = stats{k};
    condition_a = contrast_pairs(k, 1);
    condition_b = contrast_pairs(k, 2);

    significant_mask = false(size(stat.stat));
    if isfield(stat, 'mask')
        significant_mask = logical(stat.mask);
    end

    if any(significant_mask, 'all')
        candidate = abs(stat.stat);
        candidate(~significant_mask) = -inf;
        [~, linear_index] = max(candidate, [], 'all', 'linear');
        selection_label = 'peak inside significant cluster';
    else
        [~, linear_index] = max(abs(stat.stat), [], 'all', 'linear');
        selection_label = 'largest uncorrected |t|; no significant cluster';
    end

    [channel_index, time_index] = ind2sub( ...
        size(stat.stat), ...
        linear_index);

    channel_label = stat.label{channel_index};
    selected_time_ms = stat.time(time_index) .* 1000;

    source_channel_index = find( ...
        strcmpi(scalp_labels, channel_label), ...
        1);

    assert(~isempty(source_channel_index), ...
        'Could not resolve representative channel %s.', ...
        channel_label);

    values_a = squeeze( ...
        erp_uv(condition_a, :, source_channel_index, :));
    values_b = squeeze( ...
        erp_uv(condition_b, :, source_channel_index, :));

    mean_a = mean(values_a, 1, 'omitnan');
    mean_b = mean(values_b, 1, 'omitnan');
    sem_a = std(values_a, 0, 1, 'omitnan') ./ sqrt(n_subjects);
    sem_b = std(values_b, 0, 1, 'omitnan') ./ sqrt(n_subjects);

    nexttile;
    hold on;

    fill( ...
        [times_ms(:); flipud(times_ms(:))], ...
        [(mean_a + sem_a)'; flipud((mean_a - sem_a)')], ...
        line_colors(1, :), ...
        'FaceAlpha', 0.14, ...
        'EdgeColor', 'none', ...
        'HandleVisibility', 'off');

    fill( ...
        [times_ms(:); flipud(times_ms(:))], ...
        [(mean_b + sem_b)'; flipud((mean_b - sem_b)')], ...
        line_colors(2, :), ...
        'FaceAlpha', 0.14, ...
        'EdgeColor', 'none', ...
        'HandleVisibility', 'off');

    plot( ...
        times_ms, ...
        mean_a, ...
        'LineWidth', 2.2, ...
        'Color', line_colors(1, :), ...
        'DisplayName', conditions{condition_a});

    plot( ...
        times_ms, ...
        mean_b, ...
        'LineWidth', 2.2, ...
        'Color', line_colors(2, :), ...
        'DisplayName', conditions{condition_b});

    xline(0, '--', ...
        'HandleVisibility', 'off');
    xline(selected_time_ms, ':', ...
        sprintf('%.0f ms', selected_time_ms), ...
        'HandleVisibility', 'off');
    yline(0, ':', ...
        'HandleVisibility', 'off');

    xlim([-200 1000]);
    xlabel('Time (ms)');
    ylabel('Amplitude (\muV)');
    title(sprintf( ...
        '%s at %s (%s)', ...
        contrast_pretty{k}, ...
        channel_label, ...
        selection_label));
    legend('Location', 'best');
    grid on;
    box off;
end

sgtitle(sprintf( ...
    'STERN representative paired ERP waveforms (N = %d)', ...
    n_subjects));

exportgraphics(fig, waveform_figure, 'Resolution', 300);
close(fig);

fprintf('\n=== WRITING STATISTICAL SUMMARY ===\n');

summary_file = fullfile( ...
    summary_dir, ...
    'stern_erp_cluster_statistics_summary.txt');

fid = fopen(summary_file, 'w');
assert(fid ~= -1, ...
    'Could not create statistical summary: %s', summary_file);

fprintf(fid, '=== STERN ERP CLUSTER STATISTICS SUMMARY ===\n');
fprintf(fid, 'FieldTrip directory: %s\n', fieldtrip_dir);
fprintf(fid, 'Subjects: %d\n', n_subjects);
fprintf(fid, 'Conditions: %s\n', strjoin(conditions, ', '));
fprintf(fid, 'Channels: %d scalp EEG channels\n', n_channels);
fprintf(fid, 'Statistical interval: 0 to 1000 ms\n');
fprintf(fid, 'Test: dependent-samples t\n');
fprintf(fid, 'Correction: channel x time cluster-based permutation\n');
fprintf(fid, 'Cluster-forming alpha: 0.05\n');
fprintf(fid, 'Cluster statistic: maxsum\n');
fprintf(fid, 'Minimum neighbouring channels: 2\n');
fprintf(fid, 'Test tails: two-sided\n');
fprintf(fid, 'Corrected alpha: 0.05 using correcttail=alpha\n');
fprintf(fid, 'Randomization: all possible within-subject sign permutations\n');
fprintf(fid, ['Probability handling: FieldTrip Monte Carlo layer; ' ...
    'statfun-level computeprob left at default no\n']);
fprintf(fid, 'Neighbour definition: symmetric %d-nearest graph\n', k_nearest);
fprintf(fid, 'Neighbour degree min/median/max: %d / %.1f / %d\n', ...
    min(neighbour_degree), ...
    median(neighbour_degree), ...
    max(neighbour_degree));

for k = 1:numel(stats)
    stat = stats{k};

    positive_p = [];
    negative_p = [];

    if isfield(stat, 'posclusters') && ~isempty(stat.posclusters)
        positive_p = [stat.posclusters.prob];
    end

    if isfield(stat, 'negclusters') && ~isempty(stat.negclusters)
        negative_p = [stat.negclusters.prob];
    end

    significant_count = ...
        sum(positive_p < 0.05) + ...
        sum(negative_p < 0.05);

    fprintf(fid, '\n%s\n', contrast_pretty{k});
    fprintf(fid, 'Positive cluster p-values: %s\n', ...
        vector_to_text(positive_p));
    fprintf(fid, 'Negative cluster p-values: %s\n', ...
        vector_to_text(negative_p));
    fprintf(fid, 'Significant corrected clusters: %d\n', ...
        significant_count);
end

fprintf(fid, '\nInterpretation note:\n');
fprintf(fid, ...
    ['A significant cluster supports a condition difference over a connected ' ...
     'set of channel-time samples. It does not justify assigning the effect ' ...
     'to every individual channel or time point inside the cluster.\n']);

fprintf(fid, '\nOutputs:\n');
fprintf(fid, 'Cluster table: %s\n', cluster_table_file);
fprintf(fid, 'Neighbour table: %s\n', neighbour_table_file);
fprintf(fid, 'Neighbour figure: %s\n', neighbour_figure);
fprintf(fid, 'Cluster t-map figure: %s\n', tmap_figure);
fprintf(fid, 'Representative waveforms: %s\n', waveform_figure);

fclose(fid);

fprintf('\n=== STERN ERP CLUSTER STATISTICS PASSED ===\n');
fprintf('CLUSTER_TABLE=%s\n', cluster_table_file);
fprintf('NEIGHBOUR_TABLE=%s\n', neighbour_table_file);
fprintf('NEIGHBOUR_FIGURE=%s\n', neighbour_figure);
fprintf('TMAP_FIGURE=%s\n', tmap_figure);
fprintf('WAVEFORM_FIGURE=%s\n', waveform_figure);
fprintf('SUMMARY=%s\n', summary_file);

function [rows, description] = summarize_clusters( ...
    stat, ...
    contrast_name, ...
    alpha)

    rows = empty_cluster_rows();
    descriptions = strings(0, 1);

    if isfield(stat, 'posclusters') && ...
       ~isempty(stat.posclusters)

        for index = 1:numel(stat.posclusters)
            mask = stat.posclusterslabelmat == index;
            cluster = stat.posclusters(index);

            [rows, line] = append_cluster_row( ...
                rows, ...
                stat, ...
                mask, ...
                contrast_name, ...
                'positive', ...
                index, ...
                cluster.prob, ...
                cluster.clusterstat, ...
                alpha);

            descriptions(end+1, 1) = line; %#ok<AGROW>
        end
    end

    if isfield(stat, 'negclusters') && ...
       ~isempty(stat.negclusters)

        for index = 1:numel(stat.negclusters)
            mask = stat.negclusterslabelmat == index;
            cluster = stat.negclusters(index);

            [rows, line] = append_cluster_row( ...
                rows, ...
                stat, ...
                mask, ...
                contrast_name, ...
                'negative', ...
                index, ...
                cluster.prob, ...
                cluster.clusterstat, ...
                alpha);

            descriptions(end+1, 1) = line; %#ok<AGROW>
        end
    end

    if isempty(descriptions)
        description = sprintf( ...
            '%s: no positive or negative clusters formed.', ...
            contrast_name);
    else
        description = strjoin(descriptions, newline);
    end
end

function rows = empty_cluster_rows()
    rows.contrast = strings(0, 1);
    rows.sign = strings(0, 1);
    rows.cluster_index = [];
    rows.pvalue = [];
    rows.clusterstat = [];
    rows.significant = [];
    rows.time_start_ms = [];
    rows.time_end_ms = [];
    rows.n_channel_time_samples = [];
    rows.n_channels = [];
    rows.channels = strings(0, 1);
    rows.peak_t = [];
    rows.peak_channel = strings(0, 1);
    rows.peak_time_ms = [];
end

function [rows, line] = append_cluster_row( ...
    rows, ...
    stat, ...
    mask, ...
    contrast_name, ...
    sign_name, ...
    cluster_index, ...
    pvalue, ...
    clusterstat, ...
    alpha)

    [channel_indices, time_indices] = find(mask);

    unique_channel_indices = unique(channel_indices);
    unique_time_indices = unique(time_indices);

    cluster_t = stat.stat;
    cluster_t(~mask) = NaN;

    if strcmp(sign_name, 'positive')
        [peak_t, peak_linear_index] = max( ...
            cluster_t, ...
            [], ...
            'all', ...
            'omitnan', ...
            'linear');
    else
        [peak_t, peak_linear_index] = min( ...
            cluster_t, ...
            [], ...
            'all', ...
            'omitnan', ...
            'linear');
    end

    [peak_channel_index, peak_time_index] = ind2sub( ...
        size(stat.stat), ...
        peak_linear_index);

    rows.contrast(end+1, 1) = string(contrast_name);
    rows.sign(end+1, 1) = string(sign_name);
    rows.cluster_index(end+1, 1) = cluster_index;
    rows.pvalue(end+1, 1) = pvalue;
    rows.clusterstat(end+1, 1) = clusterstat;
    rows.significant(end+1, 1) = pvalue < alpha;
    rows.time_start_ms(end+1, 1) = ...
        min(stat.time(unique_time_indices)) .* 1000;
    rows.time_end_ms(end+1, 1) = ...
        max(stat.time(unique_time_indices)) .* 1000;
    rows.n_channel_time_samples(end+1, 1) = nnz(mask);
    rows.n_channels(end+1, 1) = numel(unique_channel_indices);
    rows.channels(end+1, 1) = strjoin( ...
        string(stat.label(unique_channel_indices)), ...
        ',');
    rows.peak_t(end+1, 1) = peak_t;
    rows.peak_channel(end+1, 1) = ...
        string(stat.label{peak_channel_index});
    rows.peak_time_ms(end+1, 1) = ...
        stat.time(peak_time_index) .* 1000;

    line = sprintf( ...
        ['%s %s cluster %d: p=%.6f; clusterstat=%.6f; ' ...
         '%.0f–%.0f ms; %d channels; %d samples.'], ...
        contrast_name, ...
        sign_name, ...
        cluster_index, ...
        pvalue, ...
        clusterstat, ...
        rows.time_start_ms(end), ...
        rows.time_end_ms(end), ...
        rows.n_channels(end), ...
        rows.n_channel_time_samples(end));
end

function text = vector_to_text(values)
    if isempty(values)
        text = 'none';
        return;
    end

    parts = arrayfun( ...
        @(x) sprintf('%.6f', x), ...
        values, ...
        'UniformOutput', false);

    text = strjoin(parts, ', ');
end
