results_dir = getenv('STERN_RESULTS_DIR');

erp_mat_file = fullfile( ...
    results_dir, ...
    'mat', ...
    'stern_all_channel_subject_erp.mat');

direct_oz_table_file = fullfile( ...
    results_dir, ...
    'tables', ...
    'stern_OZ_subject_level_erp.tsv');

cluster_table_file = fullfile( ...
    results_dir, ...
    'tables', ...
    'stern_erp_cluster_results.tsv');

assert(isfile(erp_mat_file), ...
    'ERP MAT file not found: %s', erp_mat_file);
assert(isfile(direct_oz_table_file), ...
    ['Direct Oz ERP table not found: %s. Rerun stage 2 before ' ...
     'finalization.'], direct_oz_table_file);
assert(isfile(cluster_table_file), ...
    'Cluster table not found: %s', cluster_table_file);

figure_dir  = fullfile(results_dir, 'figures');
table_dir   = fullfile(results_dir, 'tables');
summary_dir = fullfile(results_dir, 'summaries');

if ~isfolder(figure_dir), mkdir(figure_dir); end
if ~isfolder(table_dir), mkdir(table_dir); end
if ~isfolder(summary_dir), mkdir(summary_dir); end

loaded = load(erp_mat_file);

erp_uv       = double(loaded.erp_uv);
times_ms     = double(loaded.times_ms(:)');
scalp_labels = cellstr(string(loaded.scalp_labels));
conditions   = cellstr(string(loaded.conditions));
subjects     = cellstr(string(loaded.subjects));

n_conditions = size(erp_uv, 1);
n_subjects   = size(erp_uv, 2);
n_times      = numel(times_ms);

assert(isequal(size(erp_uv), [3 13 69 151]), ...
    'Unexpected ERP array size: %s', mat2str(size(erp_uv)));
assert(all(isfinite(erp_uv), 'all'), ...
    'ERP array contains non-finite values.');
assert(n_times == 151, ...
    'Expected 151 ERP time points, found %d.', n_times);
assert(all(diff(times_ms) > 0), ...
    'ERP time vector is not strictly increasing.');
assert(abs(times_ms(1) + 200) < 1e-6 && ...
       abs(times_ms(end) - 1000) < 1e-6, ...
    'Unexpected ERP time range: %.6f to %.6f ms.', ...
    times_ms(1), times_ms(end));
assert(isequal(string(conditions(:))', ...
    ["Ignore" "Memorize" "Probe"]), ...
    'Unexpected condition order: %s', strjoin(conditions, ', '));

fprintf('\n=== VALIDATING OZ ERP NUMERIC PROVENANCE ===\n');

oz_idx = find(strcmpi(scalp_labels, 'OZ'), 1);
assert(~isempty(oz_idx), 'OZ was not found.');

oz_values = squeeze(erp_uv(:, :, oz_idx, :));
assert(isequal(size(oz_values), [3 13 151]), ...
    'Unexpected Oz ERP size: %s', mat2str(size(oz_values)));

direct_table = readtable( ...
    direct_oz_table_file, ...
    'FileType', 'text', ...
    'Delimiter', '\t');

required_variables = { ...
    'time_ms', ...
    'subject', ...
    'condition', ...
    'amplitude_uv'};

assert(all(ismember(required_variables, ...
    direct_table.Properties.VariableNames)), ...
    'Direct Oz table is missing required columns.');

direct_oz = nan(n_conditions, n_subjects, n_times);

table_subject = string(direct_table.subject);
table_condition = string(direct_table.condition);

for c = 1:n_conditions
    for s = 1:n_subjects
        row_mask = strcmpi(table_condition, conditions{c}) & ...
                   strcmpi(table_subject, subjects{s});

        rows = direct_table(row_mask, :);

        assert(height(rows) == n_times, ...
            ['Expected %d direct Oz samples for %s/%s, found %d.'], ...
            n_times, conditions{c}, subjects{s}, height(rows));

        [sorted_time, order] = sort(double(rows.time_ms));

        assert(max(abs(sorted_time(:) - times_ms(:))) < 1e-6, ...
            'Direct Oz time vector mismatch for %s/%s.', ...
            conditions{c}, subjects{s});

        direct_oz(c, s, :) = reshape( ...
            double(rows.amplitude_uv(order)), ...
            1, ...
            1, ...
            n_times);
    end
end

assert(all(isfinite(direct_oz), 'all'), ...
    'Direct Oz reconstruction contains non-finite values.');

max_direct_difference_uv = max( ...
    abs(direct_oz - oz_values), ...
    [], ...
    'all');

assert(max_direct_difference_uv < 1e-9, ...
    ['All-channel Oz values do not reproduce the independently exported ' ...
     'subject-level Oz table. Maximum difference: %.12g uV.'], ...
    max_direct_difference_uv);

baseline_mask = times_ms >= -200 & times_ms <= 0;
subject_baseline_uv = mean(oz_values(:, :, baseline_mask), 3);
max_abs_subject_baseline_uv = max( ...
    abs(subject_baseline_uv), ...
    [], ...
    'all');

assert(max_abs_subject_baseline_uv < 2, ...
    ['Baseline residual is unexpectedly large at Oz: %.6f uV. ' ...
     'Do not export figures.'], ...
    max_abs_subject_baseline_uv);

grand_mean = squeeze(mean(oz_values, 2));
grand_sem = squeeze(std(oz_values, 0, 2)) ./ sqrt(n_subjects);

assert(isequal(size(grand_mean), [3 151]), ...
    'Unexpected grand-mean size: %s', mat2str(size(grand_mean)));
assert(all(isfinite(grand_mean), 'all') && ...
       all(isfinite(grand_sem), 'all'), ...
    'Grand-average or SEM contains non-finite values.');

max_abs_subject_oz_uv = max(abs(oz_values), [], 'all');
max_abs_grand_mean_uv = max(abs(grand_mean), [], 'all');
max_adjacent_grand_change_uv = max( ...
    abs(diff(grand_mean, 1, 2)), ...
    [], ...
    'all');

assert(max_abs_subject_oz_uv < 500, ...
    ['Subject-level Oz amplitude exceeds the broad safety threshold: ' ...
     '%.6f uV. Do not export figures.'], ...
    max_abs_subject_oz_uv);
assert(max_abs_grand_mean_uv < 100, ...
    ['Grand-average Oz amplitude exceeds the broad safety threshold: ' ...
     '%.6f uV. Do not export figures.'], ...
    max_abs_grand_mean_uv);
assert(max_adjacent_grand_change_uv < 50, ...
    ['Grand-average Oz waveform contains an implausibly abrupt adjacent ' ...
     'sample change: %.6f uV. Do not export figures.'], ...
    max_adjacent_grand_change_uv);

fprintf('DIRECT_OZ_MAX_DIFFERENCE_UV=%.12g\n', ...
    max_direct_difference_uv);
fprintf('MAX_ABS_SUBJECT_BASELINE_UV=%.9f\n', ...
    max_abs_subject_baseline_uv);
fprintf('MAX_ABS_SUBJECT_OZ_UV=%.9f\n', ...
    max_abs_subject_oz_uv);
fprintf('MAX_ABS_GRAND_MEAN_UV=%.9f\n', ...
    max_abs_grand_mean_uv);
fprintf('MAX_ADJACENT_GRAND_CHANGE_UV=%.9f\n', ...
    max_adjacent_grand_change_uv);

fprintf('\n=== EXPORTING AUDITABLE OZ GRAND-AVERAGE TABLE ===\n');

oz_grand_table = table( ...
    times_ms(:), ...
    grand_mean(1, :)', ...
    grand_sem(1, :)', ...
    grand_mean(2, :)', ...
    grand_sem(2, :)', ...
    grand_mean(3, :)', ...
    grand_sem(3, :)', ...
    'VariableNames', { ...
        'time_ms', ...
        'Ignore_mean_uv', ...
        'Ignore_sem_uv', ...
        'Memorize_mean_uv', ...
        'Memorize_sem_uv', ...
        'Probe_mean_uv', ...
        'Probe_sem_uv'});

oz_grand_table_file = fullfile( ...
    table_dir, ...
    'stern_OZ_grand_average_erp_final.tsv');

writetable( ...
    oz_grand_table, ...
    oz_grand_table_file, ...
    'FileType', 'text', ...
    'Delimiter', '\t');

fprintf('\n=== CREATING RENDERER-SAFE OZ ERP FIGURE ===\n');

line_colors = lines(n_conditions);

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Renderer', 'painters', ...
    'Position', [100 100 1250 760]);

ax = axes(fig);
hold(ax, 'on');

line_handles = gobjects(n_conditions, 1);

for c = 1:n_conditions
    line_handles(c) = plot( ...
        ax, ...
        times_ms, ...
        grand_mean(c, :), ...
        '-', ...
        'LineWidth', 2.6, ...
        'Color', line_colors(c, :), ...
        'DisplayName', conditions{c});
end

assert(all(arrayfun(@(h) numel(h.XData) == n_times, line_handles)), ...
    'One or more ERP line objects have incomplete XData.');
assert(all(arrayfun(@(h) all(isfinite(h.YData)), line_handles)), ...
    'One or more ERP line objects have invalid YData.');

xline(ax, 0, '--', 'Stimulus onset', ...
    'LabelVerticalAlignment', 'bottom', ...
    'HandleVisibility', 'off');
yline(ax, 0, ':', 'HandleVisibility', 'off');

xlim(ax, [-200 1000]);
y_limit = symmetric_limit(grand_mean);
ylim(ax, [-y_limit y_limit]);

xlabel(ax, 'Time (ms)');
ylabel(ax, 'Amplitude (\muV)');
title(ax, { ...
    sprintf('STERN grand-average ERP at Oz (N = %d)', n_subjects), ...
    'Solid lines: grand means; SEM values are provided in the companion TSV'});
legend(ax, 'Location', 'northeast');
grid(ax, 'on');
box(ax, 'off');
set(ax, 'FontSize', 13, 'Layer', 'top');

oz_final_png = fullfile( ...
    figure_dir, ...
    'stern_grand_average_erp_OZ_final.png');

oz_final_svg = fullfile( ...
    figure_dir, ...
    'stern_grand_average_erp_OZ_final.svg');

export_renderer_safe(fig, oz_final_png, oz_final_svg);
close(fig);

fprintf('\n=== CREATING RENDERER-SAFE REPRESENTATIVE WAVEFORMS ===\n');

contrast_pretty = { ...
    'Memorize - Ignore', ...
    'Probe - Memorize', ...
    'Probe - Ignore'};

contrast_pairs = [ ...
    2 1; ...
    3 2; ...
    3 1];

stat_files = { ...
    'stern_erp_cluster_Memorize_minus_Ignore.mat', ...
    'stern_erp_cluster_Probe_minus_Memorize.mat', ...
    'stern_erp_cluster_Probe_minus_Ignore.mat'};

final_waveform_png = fullfile( ...
    figure_dir, ...
    'stern_erp_cluster_representative_waveforms_final.png');

final_waveform_svg = fullfile( ...
    figure_dir, ...
    'stern_erp_cluster_representative_waveforms_final.svg');

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Renderer', 'painters', ...
    'Position', [100 100 1550 1050]);

layout = tiledlayout(fig, 3, 1, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

pair_colors = lines(2);

for k = 1:3
    stat_path = fullfile(results_dir, 'mat', stat_files{k});
    assert(isfile(stat_path), ...
        'Statistical MAT file not found: %s', stat_path);

    stat_loaded = load(stat_path);
    stat = stat_loaded.stat;

    significant_mask = false(size(stat.stat));
    if isfield(stat, 'mask')
        significant_mask = logical(stat.mask);
    end

    if any(significant_mask, 'all')
        candidate = abs(stat.stat);
        candidate(~significant_mask) = -inf;
        [~, linear_index] = max(candidate, [], 'all', 'linear');
        selection_label = 'peak inside corrected cluster';
    else
        [~, linear_index] = max(abs(stat.stat), [], 'all', 'linear');
        selection_label = 'largest uncorrected |t|';
    end

    [channel_index, time_index] = ind2sub( ...
        size(stat.stat), ...
        linear_index);

    channel_label = stat.label{channel_index};
    selected_time_ms = stat.time(time_index) .* 1000;

    source_channel_index = find( ...
        strcmpi(scalp_labels, channel_label), ...
        1);

    assert(~isempty(source_channel_index), ...
        'Could not resolve representative channel %s.', ...
        channel_label);

    condition_a = contrast_pairs(k, 1);
    condition_b = contrast_pairs(k, 2);

    values_a = squeeze( ...
        erp_uv(condition_a, :, source_channel_index, :));
    values_b = squeeze( ...
        erp_uv(condition_b, :, source_channel_index, :));

    mean_a = mean(values_a, 1);
    mean_b = mean(values_b, 1);

    assert(all(isfinite(mean_a)) && all(isfinite(mean_b)), ...
        'Representative waveform contains non-finite values.');

    ax = nexttile(layout);
    hold(ax, 'on');

    line_a = plot( ...
        ax, ...
        times_ms, ...
        mean_a, ...
        '-', ...
        'LineWidth', 2.4, ...
        'Color', pair_colors(1, :), ...
        'DisplayName', conditions{condition_a});

    line_b = plot( ...
        ax, ...
        times_ms, ...
        mean_b, ...
        '-', ...
        'LineWidth', 2.4, ...
        'Color', pair_colors(2, :), ...
        'DisplayName', conditions{condition_b});

    assert(numel(line_a.XData) == n_times && ...
           numel(line_b.XData) == n_times, ...
        'Representative line object has incomplete XData.');

    xline(ax, 0, '--', 'HandleVisibility', 'off');
    xline(ax, selected_time_ms, ':', ...
        sprintf('%.0f ms', selected_time_ms), ...
        'HandleVisibility', 'off');
    yline(ax, 0, ':', 'HandleVisibility', 'off');

    xlim(ax, [-200 1000]);
    pair_limit = symmetric_limit([mean_a; mean_b]);
    ylim(ax, [-pair_limit pair_limit]);

    xlabel(ax, 'Time (ms)');
    ylabel(ax, 'Amplitude (\muV)');
    title(ax, sprintf( ...
        '%s at %s (%s)', ...
        contrast_pretty{k}, ...
        channel_label, ...
        selection_label));
    legend(ax, 'Location', 'best');
    grid(ax, 'on');
    box(ax, 'off');
    set(ax, 'FontSize', 12, 'Layer', 'top');
end

title(layout, sprintf( ...
    'STERN representative paired ERP waveforms (N = %d)', ...
    n_subjects));

export_renderer_safe(fig, final_waveform_png, final_waveform_svg);
close(fig);

fprintf('\n=== CREATING FINAL CLUSTER TABLE ===\n');

cluster_table = readtable( ...
    cluster_table_file, ...
    'FileType', 'text', ...
    'Delimiter', '\t');

exact_permutations = 8192;
across_contrast_alpha = 0.05 / 3;

p_display = strings(height(cluster_table), 1);

for i = 1:height(cluster_table)
    if cluster_table.pvalue(i) == 0
        p_display(i) = sprintf('< %.6f', 1 / exact_permutations);
    else
        p_display(i) = sprintf('%.6f', cluster_table.pvalue(i));
    end
end

cluster_table.pvalue_display = p_display;
cluster_table.significant_within_contrast_0_05 = ...
    cluster_table.pvalue < 0.05;
cluster_table.significant_across_three_contrasts_0_016667 = ...
    cluster_table.pvalue < across_contrast_alpha;

final_cluster_table_file = fullfile( ...
    table_dir, ...
    'stern_erp_cluster_results_final.tsv');

writetable( ...
    cluster_table, ...
    final_cluster_table_file, ...
    'FileType', 'text', ...
    'Delimiter', '\t');

fprintf('\n=== WRITING ERP FINALIZATION SUMMARY ===\n');

summary_file = fullfile( ...
    summary_dir, ...
    'stern_erp_finalization_summary.txt');

fid = fopen(summary_file, 'w');
assert(fid ~= -1, ...
    'Could not create finalization summary: %s', summary_file);

fprintf(fid, '=== STERN ERP FINALIZATION SUMMARY ===\n');
fprintf(fid, 'Subjects: %d\n', n_subjects);
fprintf(fid, 'Conditions: %s\n', strjoin(conditions, ', '));
fprintf(fid, 'Scalp EEG channels: 69\n');
fprintf(fid, 'ERP array: %s\n', mat2str(size(erp_uv)));
fprintf(fid, 'Non-finite values: 0\n');
fprintf(fid, 'Direct Oz table maximum difference: %.12g uV\n', ...
    max_direct_difference_uv);
fprintf(fid, 'Maximum absolute subject baseline residual: %.9f uV\n', ...
    max_abs_subject_baseline_uv);
fprintf(fid, 'Maximum absolute subject-level Oz amplitude: %.9f uV\n', ...
    max_abs_subject_oz_uv);
fprintf(fid, 'Maximum absolute Oz grand mean: %.9f uV\n', ...
    max_abs_grand_mean_uv);
fprintf(fid, 'Maximum adjacent grand-mean change: %.9f uV\n', ...
    max_adjacent_grand_change_uv);
fprintf(fid, 'Exact within-subject permutations: %d\n', ...
    exact_permutations);
fprintf(fid, 'Minimum reportable non-zero exact probability: %.9f\n', ...
    1 / exact_permutations);
fprintf(fid, 'Additional conservative alpha across 3 contrasts: %.9f\n', ...
    across_contrast_alpha);
fprintf(fid, '\nFigure export safeguards:\n');
fprintf(fid, ...
    ['Oz values were independently reconstructed from the direct ' ...
     'subject-level Oz table and required to match the all-channel MAT ' ...
     'array before plotting.\n']);
fprintf(fid, ...
    ['Waveform figures were rendered with MATLAB painters and exported ' ...
     'to both vector SVG and 300-dpi PNG. Transparent patches were not ' ...
     'used.\n']);
fprintf(fid, ...
    ['Grand-mean and SEM values were exported to a companion TSV before ' ...
     'figure creation.\n']);
fprintf(fid, '\nInterpretation constraint from the event audit:\n');
fprintf(fid, ...
    ['Memorize and Ignore epochs contain letter events at 0 ms and form ' ...
     'the primary event-matched contrast.\n']);
fprintf(fid, ...
    ['Probe epochs contain r-prefixed probe events at 0 ms followed by ' ...
     'response/correctness markers, so Probe comparisons represent broader ' ...
     'task-phase differences rather than a specific encoding-condition effect.\n']);
fprintf(fid, '\nPrimary event-matched contrast:\n');
fprintf(fid, ...
    ['Memorize - Ignore: positive cluster 440-552 ms, p=0.015869; ' ...
     'negative cluster 632-760 ms, p=0.000366.\n']);
fprintf(fid, '\nFinal outputs:\n');
fprintf(fid, 'Oz grand-average table: %s\n', oz_grand_table_file);
fprintf(fid, 'Oz waveform PNG: %s\n', oz_final_png);
fprintf(fid, 'Oz waveform SVG: %s\n', oz_final_svg);
fprintf(fid, 'Representative waveform PNG: %s\n', final_waveform_png);
fprintf(fid, 'Representative waveform SVG: %s\n', final_waveform_svg);
fprintf(fid, 'Cluster table: %s\n', final_cluster_table_file);

fclose(fid);

fprintf('\n=== STERN ERP FINALIZATION PASSED ===\n');
fprintf('OZ_GRAND_TABLE=%s\n', oz_grand_table_file);
fprintf('OZ_FINAL_PNG=%s\n', oz_final_png);
fprintf('OZ_FINAL_SVG=%s\n', oz_final_svg);
fprintf('WAVEFORM_FINAL_PNG=%s\n', final_waveform_png);
fprintf('WAVEFORM_FINAL_SVG=%s\n', final_waveform_svg);
fprintf('FINAL_CLUSTER_TABLE=%s\n', final_cluster_table_file);
fprintf('SUMMARY=%s\n', summary_file);

function limit_value = symmetric_limit(values)
    max_value = max(abs(values), [], 'all');

    if ~isfinite(max_value) || max_value == 0
        max_value = 1;
    end

    limit_value = max( ...
        1, ...
        ceil((max_value * 1.15) * 2) / 2);
end

function export_renderer_safe(fig, png_file, svg_file)
    set(fig, 'Renderer', 'painters');
    drawnow;

    print(fig, png_file, '-dpng', '-r300', '-painters');
    print(fig, svg_file, '-dsvg', '-painters');

    assert(isfile(png_file), ...
        'PNG export was not created: %s', png_file);
    assert(isfile(svg_file), ...
        'SVG export was not created: %s', svg_file);

    png_info = dir(png_file);
    svg_info = dir(svg_file);

    assert(png_info.bytes > 50000, ...
        'PNG export is unexpectedly small: %d bytes.', png_info.bytes);
    assert(svg_info.bytes > 5000, ...
        'SVG export is unexpectedly small: %d bytes.', svg_info.bytes);

    image_data = imread(png_file);
    image_data = double(image_data);

    if ndims(image_data) == 3
        image_data = mean(image_data, 3);
    end

    nonwhite_fraction = mean(image_data(:) < 250);

    assert(nonwhite_fraction > 0.01, ...
        ['PNG export appears nearly blank. Non-white fraction: ' ...
         '%.6f.'], ...
        nonwhite_fraction);
end
