results_dir = getenv('STERN_RESULTS_DIR');

erp_mat_file = fullfile( ...
    results_dir, ...
    'mat', ...
    'stern_all_channel_subject_erp.mat');

cluster_table_file = fullfile( ...
    results_dir, ...
    'tables', ...
    'stern_erp_cluster_results.tsv');

assert(isfile(erp_mat_file), ...
    'ERP MAT file not found: %s', erp_mat_file);
assert(isfile(cluster_table_file), ...
    'Cluster table not found: %s', cluster_table_file);

figure_dir  = fullfile(results_dir, 'figures');
table_dir   = fullfile(results_dir, 'tables');
summary_dir = fullfile(results_dir, 'summaries');

if ~isfolder(figure_dir), mkdir(figure_dir); end
if ~isfolder(table_dir), mkdir(table_dir); end
if ~isfolder(summary_dir), mkdir(summary_dir); end

loaded = load(erp_mat_file);

erp_uv       = loaded.erp_uv;
times_ms     = double(loaded.times_ms(:)');
scalp_labels = cellstr(string(loaded.scalp_labels));
conditions   = cellstr(string(loaded.conditions));
subjects     = cellstr(string(loaded.subjects));

n_conditions = size(erp_uv, 1);
n_subjects   = size(erp_uv, 2);

assert(isequal(size(erp_uv), [3 13 69 151]), ...
    'Unexpected ERP array size: %s', mat2str(size(erp_uv)));
assert(all(isfinite(erp_uv), 'all'), ...
    'ERP array contains non-finite values.');

line_colors = lines(3);

fprintf('\n=== CREATING FINAL OZ ERP FIGURE ===\n');

oz_idx = find(strcmpi(scalp_labels, 'OZ'), 1);
assert(~isempty(oz_idx), 'OZ was not found.');

oz_values = squeeze(erp_uv(:, :, oz_idx, :));
grand_mean = squeeze(mean(oz_values, 2, 'omitnan'));
grand_sem = squeeze(std(oz_values, 0, 2, 'omitnan')) ./ sqrt(n_subjects);

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1250 760]);

hold on;

for c = 1:n_conditions
    plot( ...
        times_ms, ...
        grand_mean(c, :), ...
        'LineWidth', 2.6, ...
        'Color', line_colors(c, :), ...
        'DisplayName', conditions{c});

    plot( ...
        times_ms, ...
        grand_mean(c, :) + grand_sem(c, :), ...
        '--', ...
        'LineWidth', 0.9, ...
        'Color', line_colors(c, :), ...
        'HandleVisibility', 'off');

    plot( ...
        times_ms, ...
        grand_mean(c, :) - grand_sem(c, :), ...
        '--', ...
        'LineWidth', 0.9, ...
        'Color', line_colors(c, :), ...
        'HandleVisibility', 'off');
end

xline(0, '--', 'Stimulus onset', ...
    'LabelVerticalAlignment', 'bottom', ...
    'HandleVisibility', 'off');
yline(0, ':', 'HandleVisibility', 'off');

xlim([-200 1000]);
xlabel('Time (ms)');
ylabel('Amplitude (\muV)');
title(sprintf('STERN grand-average ERP at Oz (N = %d)', n_subjects));
legend('Location', 'northeast');
grid on;
box off;
set(gca, 'FontSize', 13);

oz_final_figure = fullfile( ...
    figure_dir, ...
    'stern_grand_average_erp_OZ_final.png');

exportgraphics(fig, oz_final_figure, 'Resolution', 300);
close(fig);

fprintf('\n=== CREATING FINAL REPRESENTATIVE WAVEFORMS ===\n');

contrast_names = { ...
    'Memorize_minus_Ignore', ...
    'Probe_minus_Memorize', ...
    'Probe_minus_Ignore'};

contrast_pretty = { ...
    'Memorize - Ignore', ...
    'Probe - Memorize', ...
    'Probe - Ignore'};

contrast_pairs = [ ...
    2 1; ...
    3 2; ...
    3 1];

stat_files = { ...
    'stern_erp_cluster_Memorize_minus_Ignore.mat', ...
    'stern_erp_cluster_Probe_minus_Memorize.mat', ...
    'stern_erp_cluster_Probe_minus_Ignore.mat'};

final_waveform_figure = fullfile( ...
    figure_dir, ...
    'stern_erp_cluster_representative_waveforms_final.png');

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1550 1050]);

tiledlayout(3, 1, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

pair_colors = lines(2);

for k = 1:3
    stat_path = fullfile(results_dir, 'mat', stat_files{k});
    assert(isfile(stat_path), ...
        'Statistical MAT file not found: %s', stat_path);

    stat_loaded = load(stat_path);
    stat = stat_loaded.stat;

    significant_mask = false(size(stat.stat));
    if isfield(stat, 'mask')
        significant_mask = logical(stat.mask);
    end

    if any(significant_mask, 'all')
        candidate = abs(stat.stat);
        candidate(~significant_mask) = -inf;
        [~, linear_index] = max(candidate, [], 'all', 'linear');
        selection_label = 'peak inside corrected cluster';
    else
        [~, linear_index] = max(abs(stat.stat), [], 'all', 'linear');
        selection_label = 'largest uncorrected |t|';
    end

    [channel_index, time_index] = ind2sub( ...
        size(stat.stat), ...
        linear_index);

    channel_label = stat.label{channel_index};
    selected_time_ms = stat.time(time_index) .* 1000;

    source_channel_index = find( ...
        strcmpi(scalp_labels, channel_label), ...
        1);

    assert(~isempty(source_channel_index), ...
        'Could not resolve representative channel %s.', ...
        channel_label);

    condition_a = contrast_pairs(k, 1);
    condition_b = contrast_pairs(k, 2);

    values_a = squeeze( ...
        erp_uv(condition_a, :, source_channel_index, :));
    values_b = squeeze( ...
        erp_uv(condition_b, :, source_channel_index, :));

    mean_a = mean(values_a, 1, 'omitnan');
    mean_b = mean(values_b, 1, 'omitnan');
    sem_a = std(values_a, 0, 1, 'omitnan') ./ sqrt(n_subjects);
    sem_b = std(values_b, 0, 1, 'omitnan') ./ sqrt(n_subjects);

    nexttile;
    hold on;

    plot( ...
        times_ms, ...
        mean_a, ...
        'LineWidth', 2.4, ...
        'Color', pair_colors(1, :), ...
        'DisplayName', conditions{condition_a});

    plot( ...
        times_ms, ...
        mean_a + sem_a, ...
        '--', ...
        'LineWidth', 0.8, ...
        'Color', pair_colors(1, :), ...
        'HandleVisibility', 'off');

    plot( ...
        times_ms, ...
        mean_a - sem_a, ...
        '--', ...
        'LineWidth', 0.8, ...
        'Color', pair_colors(1, :), ...
        'HandleVisibility', 'off');

    plot( ...
        times_ms, ...
        mean_b, ...
        'LineWidth', 2.4, ...
        'Color', pair_colors(2, :), ...
        'DisplayName', conditions{condition_b});

    plot( ...
        times_ms, ...
        mean_b + sem_b, ...
        '--', ...
        'LineWidth', 0.8, ...
        'Color', pair_colors(2, :), ...
        'HandleVisibility', 'off');

    plot( ...
        times_ms, ...
        mean_b - sem_b, ...
        '--', ...
        'LineWidth', 0.8, ...
        'Color', pair_colors(2, :), ...
        'HandleVisibility', 'off');

    xline(0, '--', 'HandleVisibility', 'off');
    xline(selected_time_ms, ':', ...
        sprintf('%.0f ms', selected_time_ms), ...
        'HandleVisibility', 'off');
    yline(0, ':', 'HandleVisibility', 'off');

    xlim([-200 1000]);
    xlabel('Time (ms)');
    ylabel('Amplitude (\muV)');
    title(sprintf( ...
        '%s at %s (%s)', ...
        contrast_pretty{k}, ...
        channel_label, ...
        selection_label));
    legend('Location', 'best');
    grid on;
    box off;
end

sgtitle(sprintf( ...
    'STERN representative paired ERP waveforms (N = %d)', ...
    n_subjects));

exportgraphics(fig, final_waveform_figure, 'Resolution', 300);
close(fig);

fprintf('\n=== CREATING FINAL CLUSTER TABLE ===\n');

cluster_table = readtable( ...
    cluster_table_file, ...
    'FileType', 'text', ...
    'Delimiter', '\t');

exact_permutations = 8192;
across_contrast_alpha = 0.05 / 3;

p_display = strings(height(cluster_table), 1);

for i = 1:height(cluster_table)
    if cluster_table.pvalue(i) == 0
        p_display(i) = sprintf('< %.6f', 1 / exact_permutations);
    else
        p_display(i) = sprintf('%.6f', cluster_table.pvalue(i));
    end
end

cluster_table.pvalue_display = p_display;
cluster_table.significant_within_contrast_0_05 = ...
    cluster_table.pvalue < 0.05;
cluster_table.significant_across_three_contrasts_0_016667 = ...
    cluster_table.pvalue < across_contrast_alpha;

final_cluster_table_file = fullfile( ...
    table_dir, ...
    'stern_erp_cluster_results_final.tsv');

writetable( ...
    cluster_table, ...
    final_cluster_table_file, ...
    'FileType', 'text', ...
    'Delimiter', '\t');

fprintf('\n=== WRITING ERP FINALIZATION SUMMARY ===\n');

summary_file = fullfile( ...
    summary_dir, ...
    'stern_erp_finalization_summary.txt');

fid = fopen(summary_file, 'w');
assert(fid ~= -1, ...
    'Could not create finalization summary: %s', summary_file);

fprintf(fid, '=== STERN ERP FINALIZATION SUMMARY ===\n');
fprintf(fid, 'Subjects: 13\n');
fprintf(fid, 'Conditions: Ignore, Memorize, Probe\n');
fprintf(fid, 'Scalp EEG channels: 69\n');
fprintf(fid, 'ERP array: [3 13 69 151]\n');
fprintf(fid, 'Non-finite values: 0\n');
fprintf(fid, 'Exact within-subject permutations: %d\n', exact_permutations);
fprintf(fid, 'Minimum reportable non-zero exact probability: %.9f\n', ...
    1 / exact_permutations);
fprintf(fid, 'Additional conservative alpha across 3 contrasts: %.9f\n', ...
    across_contrast_alpha);
fprintf(fid, '\nFigure repair:\n');
fprintf(fid, ...
    ['Transparent uncertainty patches were removed because the headless ' ...
     'MATLAB renderer obscured the mean traces in exported PNG files.\n']);
fprintf(fid, ...
    ['Final waveform figures show solid grand means and dashed SEM ' ...
     'boundaries without transparent patches.\n']);
fprintf(fid, '\nInterpretation constraint from the event audit:\n');
fprintf(fid, ...
    ['Memorize and Ignore epochs contain letter events at 0 ms and form ' ...
     'the primary event-matched contrast.\n']);
fprintf(fid, ...
    ['Probe epochs contain r-prefixed probe events at 0 ms followed by ' ...
     'response/correctness markers, so Probe comparisons represent broader ' ...
     'task-phase differences rather than a specific encoding-condition effect.\n']);
fprintf(fid, '\nPrimary event-matched contrast after conservative across-contrast threshold:\n');
fprintf(fid, ...
    ['Memorize - Ignore: positive cluster 440-552 ms, p=0.015869; ' ...
     'negative cluster 632-760 ms, p=0.000366.\n']);
fprintf(fid, '\nFinal outputs:\n');
fprintf(fid, 'Oz waveform: %s\n', oz_final_figure);
fprintf(fid, 'Representative waveforms: %s\n', final_waveform_figure);
fprintf(fid, 'Cluster table: %s\n', final_cluster_table_file);

fclose(fid);

fprintf('\n=== STERN ERP FINALIZATION PASSED ===\n');
fprintf('OZ_FINAL_FIGURE=%s\n', oz_final_figure);
fprintf('WAVEFORM_FINAL_FIGURE=%s\n', final_waveform_figure);
fprintf('FINAL_CLUSTER_TABLE=%s\n', final_cluster_table_file);
fprintf('SUMMARY=%s\n', summary_file);
