results_dir = getenv('STERN_RESULTS_DIR');

assert(~isempty(results_dir), 'STERN_RESULTS_DIR is not defined.');

erp_mat_file = fullfile( ...
    results_dir, ...
    'mat', ...
    'stern_all_channel_subject_erp.mat');

assert(isfile(erp_mat_file), ...
    'ERP MAT file not found: %s', erp_mat_file);

loaded = load(erp_mat_file);

erp_uv       = double(loaded.erp_uv);
times_ms     = double(loaded.times_ms(:));
scalp_labels = cellstr(string(loaded.scalp_labels));
conditions   = cellstr(string(loaded.conditions));
subjects     = cellstr(string(loaded.subjects));

n_conditions = size(erp_uv, 1);
n_subjects   = size(erp_uv, 2);
n_times      = numel(times_ms);

assert(isequal(size(erp_uv), [3 13 69 151]), ...
    'Unexpected ERP array size: %s', mat2str(size(erp_uv)));
assert(all(isfinite(erp_uv), 'all'), ...
    'ERP array contains non-finite values.');
assert(n_conditions == 3 && n_subjects == 13 && n_times == 151, ...
    'Unexpected ERP dimensions.');
assert(all(diff(times_ms) > 0), ...
    'ERP time vector is not strictly increasing.');
assert(abs(times_ms(1) + 200) < 1e-6 && ...
       abs(times_ms(end) - 1000) < 1e-6, ...
    'Unexpected ERP time range.');
assert(isequal(string(conditions(:))', ...
    ["Ignore" "Memorize" "Probe"]), ...
    'Unexpected condition order.');

table_dir = fullfile(results_dir, 'tables');
if ~isfolder(table_dir), mkdir(table_dir); end

fprintf('\n=== EXPORTING OZ GRAND-AVERAGE WAVEFORM TABLE ===\n');

oz_idx = find(strcmpi(scalp_labels, 'OZ'), 1);
assert(~isempty(oz_idx), 'OZ was not found.');

oz_values = squeeze(erp_uv(:, :, oz_idx, :));
assert(isequal(size(oz_values), [3 13 151]), ...
    'Unexpected Oz ERP size: %s', mat2str(size(oz_values)));

oz_mean = squeeze(mean(oz_values, 2));
oz_sem  = squeeze(std(oz_values, 0, 2)) ./ sqrt(n_subjects);

assert(all(isfinite(oz_mean), 'all') && ...
       all(isfinite(oz_sem), 'all'), ...
    'Oz mean or SEM contains non-finite values.');

oz_table = table( ...
    times_ms, ...
    oz_mean(1, :)', ...
    oz_sem(1, :)', ...
    oz_mean(2, :)', ...
    oz_sem(2, :)', ...
    oz_mean(3, :)', ...
    oz_sem(3, :)', ...
    'VariableNames', { ...
        'time_ms', ...
        'Ignore_mean_uv', ...
        'Ignore_sem_uv', ...
        'Memorize_mean_uv', ...
        'Memorize_sem_uv', ...
        'Probe_mean_uv', ...
        'Probe_sem_uv'});

oz_table_file = fullfile( ...
    table_dir, ...
    'stern_OZ_grand_average_erp_final.tsv');

writetable( ...
    oz_table, ...
    oz_table_file, ...
    'FileType', 'text', ...
    'Delimiter', '\t');

fprintf('\n=== EXPORTING REPRESENTATIVE ERP WAVEFORM TABLE ===\n');

contrast_names = { ...
    'Memorize_minus_Ignore', ...
    'Probe_minus_Memorize', ...
    'Probe_minus_Ignore'};

contrast_labels = { ...
    'Memorize - Ignore', ...
    'Probe - Memorize', ...
    'Probe - Ignore'};

contrast_pairs = [ ...
    2 1; ...
    3 2; ...
    3 1];

stat_files = { ...
    'stern_erp_cluster_Memorize_minus_Ignore.mat', ...
    'stern_erp_cluster_Probe_minus_Memorize.mat', ...
    'stern_erp_cluster_Probe_minus_Ignore.mat'};

contrast_col = strings(0, 1);
contrast_label_col = strings(0, 1);
channel_col = strings(0, 1);
selection_col = strings(0, 1);
selected_time_col = zeros(0, 1);
condition_col = strings(0, 1);
time_col = zeros(0, 1);
mean_col = zeros(0, 1);
sem_col = zeros(0, 1);

for k = 1:3
    stat_path = fullfile(results_dir, 'mat', stat_files{k});
    assert(isfile(stat_path), ...
        'Statistical MAT file not found: %s', stat_path);

    stat_loaded = load(stat_path);
    stat = stat_loaded.stat;

    significant_mask = false(size(stat.stat));
    if isfield(stat, 'mask')
        significant_mask = logical(stat.mask);
    end

    if any(significant_mask, 'all')
        candidate = abs(stat.stat);
        candidate(~significant_mask) = -inf;
        [~, linear_index] = max(candidate, [], 'all', 'linear');
        selection_label = 'peak inside corrected cluster';
    else
        [~, linear_index] = max(abs(stat.stat), [], 'all', 'linear');
        selection_label = 'largest uncorrected absolute t';
    end

    [channel_index, time_index] = ind2sub( ...
        size(stat.stat), ...
        linear_index);

    channel_label = string(stat.label{channel_index});
    selected_time_ms = double(stat.time(time_index)) * 1000;

    source_channel_index = find( ...
        strcmpi(scalp_labels, channel_label), ...
        1);

    assert(~isempty(source_channel_index), ...
        'Could not resolve representative channel %s.', ...
        channel_label);

    pair = contrast_pairs(k, :);

    for j = 1:2
        condition_index = pair(j);
        values = squeeze( ...
            erp_uv(condition_index, :, source_channel_index, :));

        assert(isequal(size(values), [13 151]), ...
            'Unexpected representative waveform size.');
        assert(all(isfinite(values), 'all'), ...
            'Representative waveform contains non-finite values.');

        waveform_mean = mean(values, 1);
        waveform_sem = std(values, 0, 1) ./ sqrt(n_subjects);

        assert(all(isfinite(waveform_mean)) && ...
               all(isfinite(waveform_sem)), ...
            'Representative mean or SEM contains non-finite values.');

        n = n_times;
        contrast_col(end+1:end+n, 1) = repmat( ...
            string(contrast_names{k}), n, 1);
        contrast_label_col(end+1:end+n, 1) = repmat( ...
            string(contrast_labels{k}), n, 1);
        channel_col(end+1:end+n, 1) = repmat( ...
            channel_label, n, 1);
        selection_col(end+1:end+n, 1) = repmat( ...
            string(selection_label), n, 1);
        selected_time_col(end+1:end+n, 1) = selected_time_ms;
        condition_col(end+1:end+n, 1) = repmat( ...
            string(conditions{condition_index}), n, 1);
        time_col(end+1:end+n, 1) = times_ms;
        mean_col(end+1:end+n, 1) = waveform_mean(:);
        sem_col(end+1:end+n, 1) = waveform_sem(:);
    end
end

representative_table = table( ...
    contrast_col, ...
    contrast_label_col, ...
    channel_col, ...
    selection_col, ...
    selected_time_col, ...
    condition_col, ...
    time_col, ...
    mean_col, ...
    sem_col, ...
    'VariableNames', { ...
        'contrast', ...
        'contrast_label', ...
        'channel', ...
        'selection', ...
        'selected_time_ms', ...
        'condition', ...
        'time_ms', ...
        'mean_uv', ...
        'sem_uv'});

assert(height(representative_table) == 3 * 2 * 151, ...
    'Unexpected representative table height: %d', ...
    height(representative_table));

representative_table_file = fullfile( ...
    table_dir, ...
    'stern_erp_representative_waveforms_final.tsv');

writetable( ...
    representative_table, ...
    representative_table_file, ...
    'FileType', 'text', ...
    'Delimiter', '\t');

fprintf('\n=== ERP WAVEFORM TABLE EXPORT PASSED ===\n');
fprintf('OZ_TABLE=%s\n', oz_table_file);
fprintf('REPRESENTATIVE_TABLE=%s\n', representative_table_file);
