eeglab_dir    = getenv('EEGLAB_DIR');
fieldtrip_dir = getenv('FIELDTRIP_DIR');
project_dir   = getenv('STERN_PROJECT');

results_dir = fullfile(project_dir, 'results');
tfr_file = fullfile(results_dir, 'mat', 'stern_subject_level_tfr_db.mat');
reference_set = fullfile( ...
    project_dir, ...
    'work', ...
    'study_datasets', ...
    'S01', ...
    'Memorize.set');

figure_dir  = fullfile(results_dir, 'figures');
table_dir   = fullfile(results_dir, 'tables');
summary_dir = fullfile(results_dir, 'summaries');
mat_dir     = fullfile(results_dir, 'mat');

assert(isfile(fullfile(eeglab_dir, 'eeglab.m')), ...
    'EEGLAB not found: %s', eeglab_dir);
assert(isfile(fullfile(fieldtrip_dir, 'ft_defaults.m')), ...
    'FieldTrip not found: %s', fieldtrip_dir);
assert(isfile(tfr_file), ...
    'TFR file not found: %s', tfr_file);
assert(isfile(reference_set), ...
    'Reference dataset not found: %s', reference_set);

folders = {figure_dir, table_dir, summary_dir, mat_dir};
for i = 1:numel(folders)
    if ~isfolder(folders{i})
        mkdir(folders{i});
    end
end

rng(1, 'twister');

cd(eeglab_dir);
[ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab('nogui'); %#ok<ASGLU>

addpath(fieldtrip_dir);
ft_defaults;

loaded = load(tfr_file);

tf_db       = loaded.tf_db;
freq_hz     = double(loaded.freq_hz(:)');
time_s      = double(loaded.time_s(:)');
labels      = cellstr(string(loaded.labels));
conditions  = cellstr(string(loaded.conditions));
subjects    = cellstr(string(loaded.subjects));

assert(isequal(size(tf_db), [3 13 69 14 50]), ...
    'Unexpected TFR array size: %s', mat2str(size(tf_db)));
assert(all(isfinite(tf_db), 'all'), ...
    'TFR array contains non-finite values.');

ignore_index = find(strcmpi(conditions, 'Ignore'), 1);
memorize_index = find(strcmpi(conditions, 'Memorize'), 1);

assert(~isempty(ignore_index) && ~isempty(memorize_index), ...
    'Could not resolve Ignore and Memorize condition indices.');

n_subjects = numel(subjects);
n_channels = numel(labels);

fprintf('\n=== LOADING REFERENCE CHANNEL LOCATIONS ===\n');

[ref_path, ref_name, ref_ext] = fileparts(reference_set);
EEG_REF = pop_loadset( ...
    'filename', [ref_name ref_ext], ...
    'filepath', ref_path);
EEG_REF = eeg_checkset(EEG_REF);

ref_labels = {EEG_REF.chanlocs.labels};
chanlocs = repmat(EEG_REF.chanlocs(1), 1, n_channels);

for ch = 1:n_channels
    idx = find(strcmpi(ref_labels, labels{ch}), 1);
    assert(~isempty(idx), ...
        'Channel %s missing from reference dataset.', labels{ch});
    chanlocs(ch) = EEG_REF.chanlocs(idx);
end

coords = [ ...
    [chanlocs.X]' ...
    [chanlocs.Y]' ...
    [chanlocs.Z]'];

assert(all(isfinite(coords), 'all'), ...
    'Channel coordinates contain non-finite values.');

elec = [];
elec.label   = labels(:);
elec.chanpos = coords;
elec.elecpos = coords;
elec.unit    = 'arbitrary';

fprintf('\n=== BUILDING SYMMETRIC CHANNEL NEIGHBOURS ===\n');

k_nearest = 4;
distance_matrix = nan(n_channels, n_channels);

for i = 1:n_channels
    for j = 1:n_channels
        distance_matrix(i, j) = norm(coords(i, :) - coords(j, :));
    end
end

adjacency = false(n_channels, n_channels);

for i = 1:n_channels
    distances = distance_matrix(i, :);
    distances(i) = inf;

    [~, order] = sort(distances, 'ascend');
    selected = order(1:k_nearest);
    adjacency(i, selected) = true;
end

adjacency = adjacency | adjacency';
adjacency(1:n_channels+1:end) = false;

neighbours = repmat( ...
    struct('label', '', 'neighblabel', {{}}), ...
    n_channels, ...
    1);

for i = 1:n_channels
    neighbours(i).label = labels{i};
    neighbours(i).neighblabel = labels(find(adjacency(i, :)));
end

neighbour_degree = sum(adjacency, 2);

assert(min(neighbour_degree) >= 4, ...
    'A channel has fewer than four neighbours.');

fprintf('NEIGHBOUR_DEGREE_MIN=%d\n', min(neighbour_degree));
fprintf('NEIGHBOUR_DEGREE_MEDIAN=%.1f\n', median(neighbour_degree));
fprintf('NEIGHBOUR_DEGREE_MAX=%d\n', max(neighbour_degree));

fprintf('\n=== BUILDING SUBJECT-LEVEL FIELDTRIP INPUTS ===\n');

memorize_data = cell(1, n_subjects);
ignore_data = cell(1, n_subjects);

for s = 1:n_subjects
    memorize = [];
    memorize.label = labels(:);
    memorize.freq = freq_hz;
    memorize.time = time_s;
    memorize.powspctrm = squeeze( ...
        tf_db(memorize_index, s, :, :, :));
    memorize.dimord = 'chan_freq_time';
    memorize.elec = elec;

    ignore = [];
    ignore.label = labels(:);
    ignore.freq = freq_hz;
    ignore.time = time_s;
    ignore.powspctrm = squeeze( ...
        tf_db(ignore_index, s, :, :, :));
    ignore.dimord = 'chan_freq_time';
    ignore.elec = elec;

    memorize_data{s} = memorize;
    ignore_data{s} = ignore;
end

fprintf('\n=== RUNNING PRIMARY TF CLUSTER TEST ===\n');
fprintf('CONTRAST=Memorize_minus_Ignore\n');
fprintf('STATFUN_COMPUTEPROB=default_no\n');
fprintf('RANDOMIZATION=all_possible_within_subject_permutations\n');

cfg = [];
cfg.channel          = 'all';
cfg.frequency        = [4 30];
cfg.latency          = [0 1.4];
cfg.parameter        = 'powspctrm';
cfg.method           = 'montecarlo';
cfg.statistic        = 'ft_statfun_depsamplesT';
cfg.correctm         = 'cluster';
cfg.clusteralpha     = 0.05;
cfg.clusterstatistic = 'maxsum';
cfg.minnbchan        = 2;
cfg.neighbours       = neighbours;
cfg.tail             = 0;
cfg.clustertail      = 0;
cfg.alpha            = 0.05;
cfg.correcttail      = 'alpha';
cfg.numrandomization = 'all';

design = zeros(2, 2 * n_subjects);
design(1, :) = [1:n_subjects 1:n_subjects];
design(2, :) = [ ...
    ones(1, n_subjects) ...
    2 .* ones(1, n_subjects)];

cfg.design = design;
cfg.uvar = 1;
cfg.ivar = 2;

stat = ft_freqstatistics( ...
    cfg, ...
    memorize_data{:}, ...
    ignore_data{:});

stat_file = fullfile( ...
    mat_dir, ...
    'stern_tf_cluster_Memorize_minus_Ignore.mat');

save(stat_file, 'stat', '-v7.3');

fprintf('\n=== SUMMARIZING TF CLUSTERS ===\n');

cluster_table = summarize_tf_clusters( ...
    stat, ...
    'Memorize_minus_Ignore', ...
    0.05, ...
    8192);

cluster_table_file = fullfile( ...
    table_dir, ...
    'stern_tf_cluster_Memorize_minus_Ignore.tsv');

writetable( ...
    cluster_table, ...
    cluster_table_file, ...
    'FileType', 'text', ...
    'Delimiter', '\t');

significant_cluster_count = sum( ...
    cluster_table.significant_p_lt_0_05);

fprintf('CLUSTERS_TOTAL=%d\n', height(cluster_table));
fprintf('CLUSTERS_SIGNIFICANT=%d\n', significant_cluster_count);

fprintf('\n=== CREATING PRIMARY DIFFERENCE FIGURE ===\n');

difference = squeeze(mean( ...
    tf_db(memorize_index, :, :, :, :) - ...
    tf_db(ignore_index, :, :, :, :), ...
    [2 3], ...
    'omitnan'));
% frequency x time

significant_mask = false(size(stat.stat));
if isfield(stat, 'mask')
    significant_mask = logical(stat.mask);
end

significant_channel_count = squeeze(sum(significant_mask, 1));
any_significant = significant_channel_count > 0;

difference_limit = max(abs(difference), [], 'all');
if difference_limit == 0
    difference_limit = 1;
end

difference_figure = fullfile( ...
    figure_dir, ...
    'stern_tf_Memorize_minus_Ignore_sensor_average.png');

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1250 820]);

imagesc(time_s, freq_hz, difference);
set(gca, 'YDir', 'normal');
hold on;

if any(any_significant, 'all')
    contour( ...
        stat.time, ...
        stat.freq, ...
        double(any_significant), ...
        [0.5 0.5], ...
        'k', ...
        'LineWidth', 1.5);
end

xline(0, '--', 'Color', [0 0 0], ...
    'HandleVisibility', 'off');
clim([-difference_limit difference_limit]);
xlabel('Time (s)');
ylabel('Frequency (Hz)');
title([ ...
    'STERN Memorize - Ignore sensor-average power ' ...
    '(black contour: at least one channel in corrected cluster)']);
colorbar;
set(gca, 'FontSize', 13);

exportgraphics(fig, difference_figure, 'Resolution', 300);
close(fig);

fprintf('\n=== CREATING SIGNIFICANT CHANNEL-COUNT MAP ===\n');

count_figure = fullfile( ...
    figure_dir, ...
    'stern_tf_Memorize_minus_Ignore_significant_channel_count.png');

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1250 820]);

imagesc( ...
    stat.time, ...
    stat.freq, ...
    significant_channel_count);

set(gca, 'YDir', 'normal');
xline(0, '--', 'Color', [1 1 1], ...
    'HandleVisibility', 'off');
xlabel('Time (s)');
ylabel('Frequency (Hz)');
title([ ...
    'Memorize - Ignore: channels belonging to corrected clusters']);
colorbar;
set(gca, 'FontSize', 13);

exportgraphics(fig, count_figure, 'Resolution', 300);
close(fig);

fprintf('\n=== CREATING REPRESENTATIVE CLUSTER FIGURES ===\n');

representative_tfr_figure = fullfile( ...
    figure_dir, ...
    'stern_tf_Memorize_minus_Ignore_representative_channel.png');

cluster_topography_figure = fullfile( ...
    figure_dir, ...
    'stern_tf_Memorize_minus_Ignore_cluster_topography.png');

if any(significant_mask, 'all')
    candidate = abs(stat.stat);
    candidate(~significant_mask) = -inf;
    [~, peak_linear_index] = max(candidate, [], 'all', 'linear');
    peak_note = 'peak inside corrected cluster';
else
    [~, peak_linear_index] = max(abs(stat.stat), [], 'all', 'linear');
    peak_note = 'largest uncorrected |t|';
end

[peak_channel_index, peak_freq_index, peak_time_index] = ind2sub( ...
    size(stat.stat), ...
    peak_linear_index);

peak_channel = stat.label{peak_channel_index};
peak_frequency = stat.freq(peak_freq_index);
peak_time = stat.time(peak_time_index);

source_channel_index = find(strcmpi(labels, peak_channel), 1);
assert(~isempty(source_channel_index), ...
    'Could not resolve peak channel %s.', peak_channel);

channel_difference = squeeze(mean( ...
    tf_db(memorize_index, :, source_channel_index, :, :) - ...
    tf_db(ignore_index, :, source_channel_index, :, :), ...
    2, ...
    'omitnan'));

channel_mask = squeeze(significant_mask(peak_channel_index, :, :));
channel_limit = max(abs(channel_difference), [], 'all');
if channel_limit == 0
    channel_limit = 1;
end

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1250 820]);

imagesc(time_s, freq_hz, channel_difference);
set(gca, 'YDir', 'normal');
hold on;

if any(channel_mask, 'all')
    contour( ...
        stat.time, ...
        stat.freq, ...
        double(channel_mask), ...
        [0.5 0.5], ...
        'k', ...
        'LineWidth', 1.5);
end

xline(0, '--', 'Color', [0 0 0], ...
    'HandleVisibility', 'off');
clim([-channel_limit channel_limit]);
xlabel('Time (s)');
ylabel('Frequency (Hz)');
title(sprintf( ...
    '%s at %s; peak %.1f Hz, %.2f s', ...
    'Memorize - Ignore', ...
    peak_channel, ...
    peak_frequency, ...
    peak_time));
colorbar;
set(gca, 'FontSize', 13);

exportgraphics(fig, representative_tfr_figure, 'Resolution', 300);
close(fig);

if any(significant_mask, 'all')
    active_freq_indices = find(any(significant_mask, [1 3]));
    active_time_indices = find(any(significant_mask, [1 2]));

    freq_start = min(stat.freq(active_freq_indices));
    freq_end = max(stat.freq(active_freq_indices));
    time_start = min(stat.time(active_time_indices));
    time_end = max(stat.time(active_time_indices));
else
    freq_start = max(4, peak_frequency - 2);
    freq_end = min(30, peak_frequency + 2);
    time_start = max(0, peak_time - 0.08);
    time_end = min(1.4, peak_time + 0.08);
end

freq_mask = freq_hz >= freq_start & freq_hz <= freq_end;
time_mask = time_s >= time_start & time_s <= time_end;

subject_channel_difference = squeeze(mean( ...
    tf_db(memorize_index, :, :, freq_mask, time_mask) - ...
    tf_db(ignore_index, :, :, freq_mask, time_mask), ...
    [4 5], ...
    'omitnan'));
% subject x channel

topography_values = mean( ...
    subject_channel_difference, ...
    1, ...
    'omitnan');

topography_limit = max(abs(topography_values), [], 'all');
if topography_limit == 0
    topography_limit = 1;
end

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 900 850]);

topoplot( ...
    topography_values, ...
    chanlocs, ...
    'electrodes', 'on', ...
    'maplimits', [-topography_limit topography_limit], ...
    'style', 'map', ...
    'shading', 'interp');

title(sprintf( ...
    ['Memorize - Ignore, %.1f-%.1f Hz, ' ...
     '%.2f-%.2f s'], ...
    freq_start, ...
    freq_end, ...
    time_start, ...
    time_end));
colorbar;

exportgraphics(fig, cluster_topography_figure, 'Resolution', 300);
close(fig);

fprintf('\n=== WRITING PRIMARY TF STATISTICS SUMMARY ===\n');

summary_file = fullfile( ...
    summary_dir, ...
    'stern_tf_primary_cluster_statistics_summary.txt');

fid = fopen(summary_file, 'w');
assert(fid ~= -1, ...
    'Could not create summary: %s', summary_file);

fprintf(fid, '=== STERN PRIMARY TF CLUSTER STATISTICS SUMMARY ===\n');
fprintf(fid, 'Contrast: Memorize - Ignore\n');
fprintf(fid, 'Interpretation: primary event-matched letter-onset contrast\n');
fprintf(fid, 'Subjects: %d\n', n_subjects);
fprintf(fid, 'Channels: %d scalp EEG channels\n', n_channels);
fprintf(fid, 'Frequency range: 4 to 30 Hz\n');
fprintf(fid, 'Time range: 0 to 1.4 s\n');
fprintf(fid, 'Input scale: dB relative to the Stage 1 baseline\n');
fprintf(fid, 'Test: dependent-samples t\n');
fprintf(fid, ...
    'Correction: channel x frequency x time cluster permutation\n');
fprintf(fid, 'Cluster-forming alpha: 0.05\n');
fprintf(fid, 'Cluster statistic: maxsum\n');
fprintf(fid, 'Minimum neighbouring channels: 2\n');
fprintf(fid, 'Test: two-sided\n');
fprintf(fid, 'Corrected alpha: 0.05\n');
fprintf(fid, 'Randomization: all possible within-subject permutations\n');
fprintf(fid, 'Exact permutation count reference: 8192\n');
fprintf(fid, 'Minimum reportable non-zero exact p: %.9f\n', 1 / 8192);
fprintf(fid, 'Neighbour graph: symmetric %d-nearest channels\n', k_nearest);
fprintf(fid, 'Neighbour degree min/median/max: %d / %.1f / %d\n', ...
    min(neighbour_degree), ...
    median(neighbour_degree), ...
    max(neighbour_degree));
fprintf(fid, 'Clusters formed: %d\n', height(cluster_table));
fprintf(fid, 'Significant corrected clusters: %d\n', ...
    significant_cluster_count);
fprintf(fid, 'Representative channel: %s\n', peak_channel);
fprintf(fid, 'Representative peak frequency: %.6f Hz\n', ...
    peak_frequency);
fprintf(fid, 'Representative peak time: %.6f s\n', peak_time);
fprintf(fid, 'Representative selection: %s\n', peak_note);
fprintf(fid, 'Cluster table: %s\n', cluster_table_file);
fprintf(fid, 'Statistical MAT: %s\n', stat_file);
fprintf(fid, 'Sensor-average difference figure: %s\n', ...
    difference_figure);
fprintf(fid, 'Significant-channel count figure: %s\n', ...
    count_figure);
fprintf(fid, 'Representative channel figure: %s\n', ...
    representative_tfr_figure);
fprintf(fid, 'Cluster topography: %s\n', ...
    cluster_topography_figure);
fprintf(fid, '\nInterpretation note:\n');
fprintf(fid, ...
    ['A significant cluster supports a condition difference over a ' ...
     'connected channel-frequency-time set. It does not make each sample ' ...
     'inside the cluster independently significant.\n']);

fclose(fid);

fprintf('\n=== STERN PRIMARY TF CLUSTER STATISTICS PASSED ===\n');
fprintf('STAT_MAT=%s\n', stat_file);
fprintf('CLUSTER_TABLE=%s\n', cluster_table_file);
fprintf('DIFFERENCE_FIGURE=%s\n', difference_figure);
fprintf('CHANNEL_COUNT_FIGURE=%s\n', count_figure);
fprintf('REPRESENTATIVE_TFR=%s\n', representative_tfr_figure);
fprintf('CLUSTER_TOPOGRAPHY=%s\n', cluster_topography_figure);
fprintf('SUMMARY=%s\n', summary_file);

function result = summarize_tf_clusters( ...
    stat, ...
    contrast_name, ...
    alpha, ...
    exact_permutations)

    contrast = strings(0, 1);
    sign_name = strings(0, 1);
    cluster_index = [];
    pvalue = [];
    pvalue_display = strings(0, 1);
    cluster_statistic = [];
    significant = [];
    time_start_s = [];
    time_end_s = [];
    frequency_start_hz = [];
    frequency_end_hz = [];
    n_channel_frequency_time_samples = [];
    n_channels = [];
    channels = strings(0, 1);
    peak_t = [];
    peak_channel = strings(0, 1);
    peak_frequency_hz = [];
    peak_time_s = [];

    if isfield(stat, 'posclusters') && ~isempty(stat.posclusters)
        for idx = 1:numel(stat.posclusters)
            mask = stat.posclusterslabelmat == idx;
            cluster = stat.posclusters(idx);

            [ ...
                contrast, ...
                sign_name, ...
                cluster_index, ...
                pvalue, ...
                pvalue_display, ...
                cluster_statistic, ...
                significant, ...
                time_start_s, ...
                time_end_s, ...
                frequency_start_hz, ...
                frequency_end_hz, ...
                n_channel_frequency_time_samples, ...
                n_channels, ...
                channels, ...
                peak_t, ...
                peak_channel, ...
                peak_frequency_hz, ...
                peak_time_s ...
            ] = append_tf_cluster( ...
                stat, ...
                mask, ...
                contrast_name, ...
                'positive', ...
                idx, ...
                cluster.prob, ...
                cluster.clusterstat, ...
                alpha, ...
                exact_permutations, ...
                contrast, ...
                sign_name, ...
                cluster_index, ...
                pvalue, ...
                pvalue_display, ...
                cluster_statistic, ...
                significant, ...
                time_start_s, ...
                time_end_s, ...
                frequency_start_hz, ...
                frequency_end_hz, ...
                n_channel_frequency_time_samples, ...
                n_channels, ...
                channels, ...
                peak_t, ...
                peak_channel, ...
                peak_frequency_hz, ...
                peak_time_s);
        end
    end

    if isfield(stat, 'negclusters') && ~isempty(stat.negclusters)
        for idx = 1:numel(stat.negclusters)
            mask = stat.negclusterslabelmat == idx;
            cluster = stat.negclusters(idx);

            [ ...
                contrast, ...
                sign_name, ...
                cluster_index, ...
                pvalue, ...
                pvalue_display, ...
                cluster_statistic, ...
                significant, ...
                time_start_s, ...
                time_end_s, ...
                frequency_start_hz, ...
                frequency_end_hz, ...
                n_channel_frequency_time_samples, ...
                n_channels, ...
                channels, ...
                peak_t, ...
                peak_channel, ...
                peak_frequency_hz, ...
                peak_time_s ...
            ] = append_tf_cluster( ...
                stat, ...
                mask, ...
                contrast_name, ...
                'negative', ...
                idx, ...
                cluster.prob, ...
                cluster.clusterstat, ...
                alpha, ...
                exact_permutations, ...
                contrast, ...
                sign_name, ...
                cluster_index, ...
                pvalue, ...
                pvalue_display, ...
                cluster_statistic, ...
                significant, ...
                time_start_s, ...
                time_end_s, ...
                frequency_start_hz, ...
                frequency_end_hz, ...
                n_channel_frequency_time_samples, ...
                n_channels, ...
                channels, ...
                peak_t, ...
                peak_channel, ...
                peak_frequency_hz, ...
                peak_time_s);
        end
    end

    result = table( ...
        contrast, ...
        sign_name, ...
        cluster_index, ...
        pvalue, ...
        pvalue_display, ...
        cluster_statistic, ...
        logical(significant), ...
        time_start_s, ...
        time_end_s, ...
        frequency_start_hz, ...
        frequency_end_hz, ...
        n_channel_frequency_time_samples, ...
        n_channels, ...
        channels, ...
        peak_t, ...
        peak_channel, ...
        peak_frequency_hz, ...
        peak_time_s, ...
        'VariableNames', { ...
            'contrast', ...
            'sign', ...
            'cluster_index', ...
            'pvalue', ...
            'pvalue_display', ...
            'cluster_statistic', ...
            'significant_p_lt_0_05', ...
            'time_start_s', ...
            'time_end_s', ...
            'frequency_start_hz', ...
            'frequency_end_hz', ...
            'n_channel_frequency_time_samples', ...
            'n_channels', ...
            'channels', ...
            'peak_t', ...
            'peak_channel', ...
            'peak_frequency_hz', ...
            'peak_time_s'});
end

function varargout = append_tf_cluster( ...
    stat, ...
    mask, ...
    contrast_name, ...
    cluster_sign, ...
    index, ...
    probability, ...
    cluster_stat, ...
    alpha, ...
    exact_permutations, ...
    contrast, ...
    sign_name, ...
    cluster_index, ...
    pvalue, ...
    pvalue_display, ...
    cluster_statistic, ...
    significant, ...
    time_start_s, ...
    time_end_s, ...
    frequency_start_hz, ...
    frequency_end_hz, ...
    n_channel_frequency_time_samples, ...
    n_channels, ...
    channels, ...
    peak_t, ...
    peak_channel, ...
    peak_frequency_hz, ...
    peak_time_s)

    [channel_indices, frequency_indices, time_indices] = ...
        ind2sub(size(mask), find(mask));

    unique_channel_indices = unique(channel_indices);
    unique_frequency_indices = unique(frequency_indices);
    unique_time_indices = unique(time_indices);

    cluster_t = stat.stat;
    cluster_t(~mask) = NaN;

    if strcmp(cluster_sign, 'positive')
        [peak_value, peak_linear_index] = max( ...
            cluster_t, ...
            [], ...
            'all', ...
            'omitnan', ...
            'linear');
    else
        [peak_value, peak_linear_index] = min( ...
            cluster_t, ...
            [], ...
            'all', ...
            'omitnan', ...
            'linear');
    end

    [peak_channel_index, peak_frequency_index, peak_time_index] = ...
        ind2sub(size(stat.stat), peak_linear_index);

    contrast(end+1, 1) = string(contrast_name);
    sign_name(end+1, 1) = string(cluster_sign);
    cluster_index(end+1, 1) = index;
    pvalue(end+1, 1) = probability;

    if probability == 0
        pvalue_display(end+1, 1) = ...
            string(sprintf('< %.6f', 1 / exact_permutations));
    else
        pvalue_display(end+1, 1) = ...
            string(sprintf('%.6f', probability));
    end

    cluster_statistic(end+1, 1) = cluster_stat;
    significant(end+1, 1) = probability < alpha;
    time_start_s(end+1, 1) = ...
        min(stat.time(unique_time_indices));
    time_end_s(end+1, 1) = ...
        max(stat.time(unique_time_indices));
    frequency_start_hz(end+1, 1) = ...
        min(stat.freq(unique_frequency_indices));
    frequency_end_hz(end+1, 1) = ...
        max(stat.freq(unique_frequency_indices));
    n_channel_frequency_time_samples(end+1, 1) = nnz(mask);
    n_channels(end+1, 1) = numel(unique_channel_indices);
    channels(end+1, 1) = strjoin( ...
        string(stat.label(unique_channel_indices)), ...
        ',');
    peak_t(end+1, 1) = peak_value;
    peak_channel(end+1, 1) = ...
        string(stat.label{peak_channel_index});
    peak_frequency_hz(end+1, 1) = ...
        stat.freq(peak_frequency_index);
    peak_time_s(end+1, 1) = ...
        stat.time(peak_time_index);

    varargout = { ...
        contrast, ...
        sign_name, ...
        cluster_index, ...
        pvalue, ...
        pvalue_display, ...
        cluster_statistic, ...
        significant, ...
        time_start_s, ...
        time_end_s, ...
        frequency_start_hz, ...
        frequency_end_hz, ...
        n_channel_frequency_time_samples, ...
        n_channels, ...
        channels, ...
        peak_t, ...
        peak_channel, ...
        peak_frequency_hz, ...
        peak_time_s};
end
