eeglab_dir    = getenv('EEGLAB_DIR');
fieldtrip_dir = getenv('FIELDTRIP_DIR');
project_dir   = getenv('STERN_PROJECT');

data_dir      = fullfile(project_dir, 'work', 'study_datasets');
cache_dir     = fullfile(project_dir, 'work', 'tf_subject_cache');
results_dir   = fullfile(project_dir, 'results');
figure_dir    = fullfile(results_dir, 'figures');
table_dir     = fullfile(results_dir, 'tables');
summary_dir   = fullfile(results_dir, 'summaries');
mat_dir       = fullfile(results_dir, 'mat');

assert(isfile(fullfile(eeglab_dir, 'eeglab.m')), ...
    'EEGLAB not found: %s', eeglab_dir);
assert(isfile(fullfile(fieldtrip_dir, 'ft_defaults.m')), ...
    'FieldTrip not found: %s', fieldtrip_dir);
assert(isfolder(data_dir), ...
    'Working dataset directory not found: %s', data_dir);

folders = {cache_dir, figure_dir, table_dir, summary_dir, mat_dir};
for i = 1:numel(folders)
    if ~isfolder(folders{i})
        mkdir(folders{i});
    end
end

rng(1, 'twister');

cd(eeglab_dir);
[ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab('nogui'); %#ok<ASGLU>

addpath(fieldtrip_dir);
ft_defaults;

subjects = arrayfun(@(x) sprintf('S%02d', x), 1:13, ...
    'UniformOutput', false);
conditions = {'Ignore', 'Memorize', 'Probe'};

foi = 4:2:30;
toi = -0.48:0.04:1.48;
baseline_window = [-0.48 -0.16];
cycles_per_frequency = 4;

reference_file = fullfile(data_dir, 'S01', 'Memorize.set');
assert(isfile(reference_file), ...
    'Reference dataset missing: %s', reference_file);

fprintf('\n=== PREPARING COMMON 69-CHANNEL MONTAGE ===\n');

EEG_REF = pop_loadset( ...
    'filename', 'Memorize.set', ...
    'filepath', fullfile(data_dir, 'S01'));
EEG_REF = eeg_checkset(EEG_REF);

ref_labels = {EEG_REF.chanlocs.labels};
eye_mask = strcmpi(ref_labels, 'LEYE') | strcmpi(ref_labels, 'REYE');
target_chanlocs = EEG_REF.chanlocs(~eye_mask);
scalp_labels = {target_chanlocs.labels};

assert(numel(scalp_labels) == 69, ...
    'Expected 69 scalp EEG channels, found %d.', numel(scalp_labels));

clear EEG_REF;

n_subjects = numel(subjects);
n_conditions = numel(conditions);
n_channels = numel(scalp_labels);
n_freqs = numel(foi);
n_times = numel(toi);

tf_db = nan( ...
    n_conditions, ...
    n_subjects, ...
    n_channels, ...
    n_freqs, ...
    n_times, ...
    'single');

qc_subject = strings(0, 1);
qc_condition = strings(0, 1);
qc_trials = [];
qc_original_channels = [];
qc_rejected_ics = [];
qc_missing_scalp_channels = [];
qc_output_channels = [];
qc_finite_fraction = [];
qc_cache_file = strings(0, 1);
qc_reused_cache = [];

fprintf('\n=== COMPUTING SUBJECT-LEVEL TIME-FREQUENCY POWER ===\n');

for s = 1:n_subjects
    for c = 1:n_conditions
        subject = subjects{s};
        condition = conditions{c};

        source_file = fullfile( ...
            data_dir, ...
            subject, ...
            [condition '.set']);

        assert(isfile(source_file), ...
            'Missing dataset: %s', source_file);

        cache_file = fullfile( ...
            cache_dir, ...
            sprintf('%s_%s_tf_db.mat', subject, condition));

        reuse_cache = false;

        if isfile(cache_file)
            cached = load(cache_file);

            required_fields = { ...
                'pow_db', ...
                'freq_hz', ...
                'time_s', ...
                'labels', ...
                'n_trials', ...
                'original_channels', ...
                'rejected_ics', ...
                'missing_scalp_channels'};

            has_fields = all(isfield(cached, required_fields));

            if has_fields
                labels_ok = isequal( ...
                    cellstr(string(cached.labels)), ...
                    scalp_labels);

                freq_ok = isequal( ...
                    double(cached.freq_hz(:)'), ...
                    double(foi));

                time_ok = max(abs( ...
                    double(cached.time_s(:)') - ...
                    double(toi))) < 1e-9;

                size_ok = isequal( ...
                    size(cached.pow_db), ...
                    [n_channels n_freqs n_times]);

                finite_ok = all(isfinite(cached.pow_db), 'all');

                reuse_cache = ...
                    labels_ok && ...
                    freq_ok && ...
                    time_ok && ...
                    size_ok && ...
                    finite_ok;
            end
        end

        if reuse_cache
            fprintf('REUSING %s %s\n', subject, condition);

            pow_db = single(cached.pow_db);
            n_trials = double(cached.n_trials);
            original_channels = double(cached.original_channels);
            rejected_ics = double(cached.rejected_ics);
            missing_scalp_channels = ...
                double(cached.missing_scalp_channels);
        else
            fprintf('\n--- %s %s ---\n', subject, condition);

            EEG = pop_loadset( ...
                'filename', [condition '.set'], ...
                'filepath', fullfile(data_dir, subject));
            EEG = eeg_checkset(EEG);

            n_trials = EEG.trials;
            original_channels = EEG.nbchan;

            rejected = [];
            if isfield(EEG, 'reject') && ...
               isfield(EEG.reject, 'gcompreject') && ...
               ~isempty(EEG.reject.gcompreject)
                rejected = find(EEG.reject.gcompreject);
            end

            rejected_ics = numel(rejected);

            if ~isempty(rejected)
                EEG = pop_subcomp(EEG, rejected, 0);
                EEG = eeg_checkset(EEG);
            end

            current_labels = {EEG.chanlocs.labels};
            eye_labels_present = intersect( ...
                current_labels, ...
                {'LEYE', 'REYE'}, ...
                'stable');

            if ~isempty(eye_labels_present)
                EEG = pop_select( ...
                    EEG, ...
                    'nochannel', ...
                    eye_labels_present);
                EEG = eeg_checkset(EEG);
            end

            current_labels = {EEG.chanlocs.labels};
            missing_labels = setdiff( ...
                scalp_labels, ...
                current_labels, ...
                'stable');

            missing_scalp_channels = numel(missing_labels);

            if missing_scalp_channels > 0
                fprintf( ...
                    'Interpolating %d channels: %s\n', ...
                    missing_scalp_channels, ...
                    strjoin(missing_labels, ', '));

                EEG = eeg_interp( ...
                    EEG, ...
                    target_chanlocs, ...
                    'spherical');
                EEG = eeg_checkset(EEG);
            end

            % Reorder explicitly to the common reference montage.
            % Selecting channels by label can preserve the dataset's original
            % order, which differs in some STERN subjects (for example S07).
            current_labels = {EEG.chanlocs.labels};
            target_indices = zeros(1, n_channels);

            for ch = 1:n_channels
                idx = find( ...
                    strcmpi(current_labels, scalp_labels{ch}), ...
                    1);

                assert(~isempty(idx), ...
                    'Channel %s missing after harmonization for %s %s.', ...
                    scalp_labels{ch}, subject, condition);

                target_indices(ch) = idx;
            end

            assert(numel(unique(target_indices)) == n_channels, ...
                'Duplicate channel mapping for %s %s.', ...
                subject, condition);

            ordered_data = EEG.data(target_indices, :, :);
            ordered_chanlocs = EEG.chanlocs(target_indices);
            ordered_labels = {ordered_chanlocs.labels};

            assert(isequal( ...
                upper(string(ordered_labels)), ...
                upper(string(scalp_labels))), ...
                'Explicit channel reordering failed for %s %s.', ...
                subject, condition);

            assert(size(ordered_data, 1) == n_channels, ...
                '%s %s has %d scalp channels after harmonization.', ...
                subject, condition, size(ordered_data, 1));

            ft_data = [];
            ft_data.label = scalp_labels(:);
            ft_data.fsample = double(EEG.srate);
            ft_data.trial = cell(1, EEG.trials);
            ft_data.time = cell(1, EEG.trials);

            trial_time = double(EEG.times) ./ 1000;

            for tr = 1:EEG.trials
                ft_data.trial{tr} = double(ordered_data(:, :, tr));
                ft_data.time{tr} = trial_time;
            end

            cfg = [];
            cfg.method = 'mtmconvol';
            cfg.output = 'pow';
            cfg.taper = 'hanning';
            cfg.foi = foi;
            cfg.t_ftimwin = cycles_per_frequency ./ foi;
            cfg.toi = toi;
            cfg.keeptrials = 'no';
            cfg.pad = 'nextpow2';
            cfg.channel = 'all';
            cfg.feedback = 'no';

            freq = ft_freqanalysis(cfg, ft_data);

            cfg_base = [];
            cfg_base.baseline = baseline_window;
            cfg_base.baselinetype = 'db';

            freq_db = ft_freqbaseline(cfg_base, freq);

            assert(isequal( ...
                size(freq_db.powspctrm), ...
                [n_channels n_freqs n_times]), ...
                ['Unexpected TFR dimensions for %s %s: %s; ' ...
                 'expected [%d %d %d].'], ...
                subject, ...
                condition, ...
                mat2str(size(freq_db.powspctrm)), ...
                n_channels, ...
                n_freqs, ...
                n_times);

            assert(all(isfinite(freq_db.powspctrm), 'all'), ...
                'Non-finite TFR values for %s %s.', ...
                subject, condition);

            pow_db = single(freq_db.powspctrm);
            freq_hz = double(freq_db.freq(:)');
            time_s = double(freq_db.time(:)');
            labels = scalp_labels; %#ok<NASGU>

            save( ...
                cache_file, ...
                'pow_db', ...
                'freq_hz', ...
                'time_s', ...
                'labels', ...
                'n_trials', ...
                'original_channels', ...
                'rejected_ics', ...
                'missing_scalp_channels', ...
                'baseline_window', ...
                'cycles_per_frequency', ...
                '-v7.3');

            clear EEG ft_data freq freq_db cached;
        end

        tf_db(c, s, :, :, :) = pow_db;

        qc_subject(end+1, 1) = string(subject); %#ok<SAGROW>
        qc_condition(end+1, 1) = string(condition); %#ok<SAGROW>
        qc_trials(end+1, 1) = n_trials; %#ok<SAGROW>
        qc_original_channels(end+1, 1) = original_channels; %#ok<SAGROW>
        qc_rejected_ics(end+1, 1) = rejected_ics; %#ok<SAGROW>
        qc_missing_scalp_channels(end+1, 1) = ...
            missing_scalp_channels; %#ok<SAGROW>
        qc_output_channels(end+1, 1) = n_channels; %#ok<SAGROW>
        qc_finite_fraction(end+1, 1) = ...
            mean(isfinite(pow_db), 'all'); %#ok<SAGROW>
        qc_cache_file(end+1, 1) = string(cache_file); %#ok<SAGROW>
        qc_reused_cache(end+1, 1) = reuse_cache; %#ok<SAGROW>

        clear pow_db cached;
    end
end

assert(all(isfinite(tf_db), 'all'), ...
    'Aggregated TFR array contains non-finite values.');

fprintf('\n=== EXPORTING TFR ARRAY AND QC TABLE ===\n');

subject_tfr_file = fullfile( ...
    mat_dir, ...
    'stern_subject_level_tfr_db.mat');

freq_hz = foi;
time_s = toi;
labels = scalp_labels;

save( ...
    subject_tfr_file, ...
    'tf_db', ...
    'freq_hz', ...
    'time_s', ...
    'labels', ...
    'conditions', ...
    'subjects', ...
    'baseline_window', ...
    'cycles_per_frequency', ...
    '-v7.3');

qc_table = table( ...
    qc_subject, ...
    qc_condition, ...
    qc_trials, ...
    qc_original_channels, ...
    qc_rejected_ics, ...
    qc_missing_scalp_channels, ...
    qc_output_channels, ...
    qc_finite_fraction, ...
    logical(qc_reused_cache), ...
    qc_cache_file, ...
    'VariableNames', { ...
        'subject', ...
        'condition', ...
        'trials', ...
        'original_channels', ...
        'rejected_ics', ...
        'interpolated_scalp_channels', ...
        'output_scalp_channels', ...
        'finite_fraction', ...
        'reused_cache', ...
        'cache_file'});

qc_table_file = fullfile( ...
    table_dir, ...
    'stern_tf_dataset_qc.tsv');

writetable( ...
    qc_table, ...
    qc_table_file, ...
    'FileType', 'text', ...
    'Delimiter', '\t');

fprintf('\n=== CREATING TIME-FREQUENCY QC FIGURE ===\n');

grand_tfr = squeeze(mean( ...
    mean(tf_db, 2, 'omitnan'), ...
    3, ...
    'omitnan'));
% condition x frequency x time

primary_difference = squeeze(mean( ...
    tf_db(2, :, :, :, :) - tf_db(1, :, :, :, :), ...
    [2 3], ...
    'omitnan'));
% frequency x time

condition_limit = max(abs(grand_tfr), [], 'all');
difference_limit = max(abs(primary_difference), [], 'all');

if condition_limit == 0
    condition_limit = 1;
end
if difference_limit == 0
    difference_limit = 1;
end

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1500 1050]);

tiledlayout(2, 2, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

for c = 1:3
    nexttile;

    imagesc( ...
        time_s, ...
        freq_hz, ...
        squeeze(grand_tfr(c, :, :)));

    set(gca, 'YDir', 'normal');
    xline(0, '--', 'Color', [0 0 0], ...
        'HandleVisibility', 'off');
    yline(8, ':', 'HandleVisibility', 'off');
    yline(12, ':', 'HandleVisibility', 'off');

    clim([-condition_limit condition_limit]);
    xlabel('Time (s)');
    ylabel('Frequency (Hz)');
    title(sprintf('%s: sensor-average power', conditions{c}));
    colorbar;
end

nexttile;

imagesc( ...
    time_s, ...
    freq_hz, ...
    primary_difference);

set(gca, 'YDir', 'normal');
xline(0, '--', 'Color', [0 0 0], ...
    'HandleVisibility', 'off');
yline(8, ':', 'HandleVisibility', 'off');
yline(12, ':', 'HandleVisibility', 'off');

clim([-difference_limit difference_limit]);
xlabel('Time (s)');
ylabel('Frequency (Hz)');
title('Memorize - Ignore: sensor-average power');
colorbar;

sgtitle(sprintf( ...
    ['STERN time-frequency QC (N = %d; dB relative to ' ...
     '%.2f to %.2f s baseline)'], ...
    n_subjects, ...
    baseline_window(1), ...
    baseline_window(2)));

qc_figure_file = fullfile( ...
    figure_dir, ...
    'stern_tf_stage1_sensor_average_qc.png');

exportgraphics(fig, qc_figure_file, 'Resolution', 300);
close(fig);

fprintf('\n=== EXPORTING BAND-WINDOW SUMMARY ===\n');

band_names = {'theta', 'alpha', 'beta'};
band_limits = [4 7; 8 12; 14 30];

window_names = { ...
    'early_0_0.3_s', ...
    'middle_0.3_0.8_s', ...
    'late_0.8_1.4_s'};

window_limits = [ ...
    0.0 0.3; ...
    0.3 0.8; ...
    0.8 1.4];

summary_subject = strings(0, 1);
summary_condition = strings(0, 1);
summary_band = strings(0, 1);
summary_window = strings(0, 1);
summary_mean_db = [];

for c = 1:n_conditions
    for s = 1:n_subjects
        for b = 1:size(band_limits, 1)
            freq_mask = ...
                freq_hz >= band_limits(b, 1) & ...
                freq_hz <= band_limits(b, 2);

            for w = 1:size(window_limits, 1)
                time_mask = ...
                    time_s >= window_limits(w, 1) & ...
                    time_s <= window_limits(w, 2);

                values = tf_db( ...
                    c, ...
                    s, ...
                    :, ...
                    freq_mask, ...
                    time_mask);

                summary_subject(end+1, 1) = ...
                    string(subjects{s}); %#ok<SAGROW>
                summary_condition(end+1, 1) = ...
                    string(conditions{c}); %#ok<SAGROW>
                summary_band(end+1, 1) = ...
                    string(band_names{b}); %#ok<SAGROW>
                summary_window(end+1, 1) = ...
                    string(window_names{w}); %#ok<SAGROW>
                summary_mean_db(end+1, 1) = ...
                    mean(values, 'all', 'omitnan'); %#ok<SAGROW>
            end
        end
    end
end

band_table = table( ...
    summary_subject, ...
    summary_condition, ...
    summary_band, ...
    summary_window, ...
    summary_mean_db, ...
    'VariableNames', { ...
        'subject', ...
        'condition', ...
        'band', ...
        'window', ...
        'sensor_average_power_db'});

band_table_file = fullfile( ...
    table_dir, ...
    'stern_tf_band_window_subject_summary.tsv');

writetable( ...
    band_table, ...
    band_table_file, ...
    'FileType', 'text', ...
    'Delimiter', '\t');

fprintf('\n=== WRITING TF STAGE 1 SUMMARY ===\n');

summary_file = fullfile( ...
    summary_dir, ...
    'stern_tf_stage1_summary.txt');

fid = fopen(summary_file, 'w');
assert(fid ~= -1, ...
    'Could not create summary: %s', summary_file);

fprintf(fid, '=== STERN TIME-FREQUENCY STAGE 1 SUMMARY ===\n');
fprintf(fid, 'EEGLAB version: %s\n', eeg_getversion);
fprintf(fid, 'MATLAB version: %s\n', version);
fprintf(fid, 'FieldTrip directory: %s\n', fieldtrip_dir);
fprintf(fid, 'Subjects: %d\n', n_subjects);
fprintf(fid, 'Conditions: %s\n', strjoin(conditions, ', '));
fprintf(fid, 'Scalp EEG channels: %d\n', n_channels);
fprintf(fid, 'Eye channels excluded: LEYE, REYE\n');
fprintf(fid, 'Frequency method: mtmconvol with Hanning taper\n');
fprintf(fid, 'Frequencies: %s Hz\n', mat2str(freq_hz));
fprintf(fid, 'Cycles per frequency: %d\n', cycles_per_frequency);
fprintf(fid, 'Times: %.2f to %.2f s in %.2f s steps\n', ...
    min(time_s), max(time_s), median(diff(time_s)));
fprintf(fid, 'Baseline: %.2f to %.2f s\n', ...
    baseline_window(1), baseline_window(2));
fprintf(fid, 'Baseline type: dB\n');
fprintf(fid, 'TFR array order: condition x subject x channel x frequency x time\n');
fprintf(fid, 'TFR array size: %s\n', mat2str(size(tf_db)));
fprintf(fid, 'TFR non-finite count: %d\n', ...
    sum(~isfinite(tf_db), 'all'));
fprintf(fid, 'Total trials represented: %d\n', sum(qc_trials));
fprintf(fid, 'Total rejected ICA components removed: %d\n', ...
    sum(qc_rejected_ics));
fprintf(fid, 'Datasets with interpolated scalp channels: %d\n', ...
    sum(qc_missing_scalp_channels > 0));
fprintf(fid, 'Subject-level TFR: %s\n', subject_tfr_file);
fprintf(fid, 'Dataset QC table: %s\n', qc_table_file);
fprintf(fid, 'Band/window table: %s\n', band_table_file);
fprintf(fid, 'QC figure: %s\n', qc_figure_file);
fprintf(fid, '\nInterpretation constraint:\n');
fprintf(fid, ...
    ['Memorize - Ignore is the primary event-matched letter-onset ' ...
     'contrast. Probe comparisons are treated as task-phase contrasts.\n']);

fclose(fid);

fprintf('\n=== STERN TIME-FREQUENCY STAGE 1 V2 PASSED ===\n');
fprintf('TFR_MAT=%s\n', subject_tfr_file);
fprintf('QC_TABLE=%s\n', qc_table_file);
fprintf('BAND_TABLE=%s\n', band_table_file);
fprintf('QC_FIGURE=%s\n', qc_figure_file);
fprintf('SUMMARY=%s\n', summary_file);
