eeglab_dir  = getenv('EEGLAB_DIR');
study_dir   = getenv('STERN_STUDY_DIR');
results_dir = getenv('STERN_RESULTS_DIR');
project_dir = getenv('STERN_PROJECT');

study_filename = 'stern_portfolio_erp.study';
study_file = fullfile(study_dir, study_filename);

assert(isfile(fullfile(eeglab_dir, 'eeglab.m')), ...
    'EEGLAB not found: %s', eeglab_dir);
assert(isfile(study_file), ...
    'STUDY not found: %s', study_file);

figure_dir = fullfile(results_dir, 'figures');
table_dir = fullfile(results_dir, 'tables');
summary_dir = fullfile(results_dir, 'summaries');
mat_dir = fullfile(results_dir, 'mat');

if ~isfolder(figure_dir), mkdir(figure_dir); end
if ~isfolder(table_dir), mkdir(table_dir); end
if ~isfolder(summary_dir), mkdir(summary_dir); end
if ~isfolder(mat_dir), mkdir(mat_dir); end

cd(eeglab_dir);
[ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab('nogui'); %#ok<ASGLU>

[STUDY, ALLEEG] = pop_loadstudy( ...
    'filename', study_filename, ...
    'filepath', study_dir);

STUDY.currentdesign = 1;

subjects = arrayfun(@(x) sprintf('S%02d', x), 1:13, ...
    'UniformOutput', false);
conditions = {'Ignore', 'Memorize', 'Probe'};

scalp_labels = { ...
    'OZ','O2','FP1','FPZ','FP2','AF7','AF3','AFZ','AF4','AF8', ...
    'F9','F7','F5','F3','F1','FZ','F2','F4','F6','F8','F10', ...
    'FT9','FT7','FC5','FC3','FC1','FCZ','FC2','FC4','FC6', ...
    'FT8','FT10','T7','C5','C3','C1','CZ','C2','C4','C6','T8', ...
    'TP9','TP7','CP5','CP3','CP1','CPZ','CP2','CP4','CP6', ...
    'TP8','TP10','P7','P5','P3','P1','PZ','P2','P4','P6','P8', ...
    'PO9','PO7','PO3','POZ','PO4','PO8','PO10','O1'};

assert(numel(scalp_labels) == 69, ...
    'Expected 69 scalp EEG labels, found %d.', numel(scalp_labels));

fprintf('\n=== EXTRACTING ALL-CHANNEL SUBJECT ERPS ===\n');

[STUDY, raw_erp, times_ms] = std_erpplot( ...
    STUDY, ...
    ALLEEG, ...
    'channels', scalp_labels, ...
    'design', 1, ...
    'timerange', [-200 1000], ...
    'noplot', 'on');

assert(numel(raw_erp) == 3, ...
    'Expected 3 condition cells, found %d.', numel(raw_erp));

n_times = numel(times_ms);
n_channels = numel(scalp_labels);
n_subjects = numel(subjects);
n_conditions = numel(conditions);

erp_uv = nan(n_conditions, n_subjects, n_channels, n_times);

for c = 1:n_conditions
    normalized = normalize_erp_array( ...
        double(raw_erp{c}), ...
        n_times, ...
        n_channels, ...
        n_subjects);

    % normalized is time x channel x subject
    erp_uv(c, :, :, :) = permute(normalized, [3 2 1]);
end

assert(sum(isnan(erp_uv), 'all') == 0, ...
    'All-channel ERP array contains NaN values.');

fprintf('ERP_ARRAY_SIZE=%s\n', mat2str(size(erp_uv)));
fprintf('ERP_NAN_COUNT=%d\n', sum(isnan(erp_uv), 'all'));

fprintf('\n=== RESOLVING CHANNEL LOCATIONS ===\n');

reference_dataset = fullfile( ...
    project_dir, ...
    'work', 'study_datasets', 'S01', 'Memorize.set');

assert(isfile(reference_dataset), ...
    'Reference dataset not found: %s', reference_dataset);

[ref_path, ref_name, ref_ext] = fileparts(reference_dataset);
EEG_REF = pop_loadset( ...
    'filename', [ref_name ref_ext], ...
    'filepath', ref_path);
EEG_REF = eeg_checkset(EEG_REF);

ref_labels = {EEG_REF.chanlocs.labels};
chanlocs = repmat(EEG_REF.chanlocs(1), 1, n_channels);

for ch = 1:n_channels
    idx = find(strcmpi(ref_labels, scalp_labels{ch}), 1);

    assert(~isempty(idx), ...
        'Channel %s missing from reference dataset.', scalp_labels{ch});

    chanlocs(ch) = EEG_REF.chanlocs(idx);
end

fprintf('\n=== EXPORTING ALL-CHANNEL ERP DATA ===\n');

mat_file = fullfile(mat_dir, 'stern_all_channel_subject_erp.mat');

save(mat_file, ...
    'erp_uv', ...
    'times_ms', ...
    'scalp_labels', ...
    'conditions', ...
    'subjects', ...
    'chanlocs', ...
    '-v7.3');

windows_ms = [ ...
     80 140; ...
    180 300; ...
    300 600; ...
    600 900];

window_names = { ...
    '80_140_ms', ...
    '180_300_ms', ...
    '300_600_ms', ...
    '600_900_ms'};

window_pretty = { ...
    '80–140 ms', ...
    '180–300 ms', ...
    '300–600 ms', ...
    '600–900 ms'};

subject_col = strings(0, 1);
condition_col = strings(0, 1);
channel_col = strings(0, 1);
window_col = strings(0, 1);
mean_uv_col = [];

window_values = cell(size(windows_ms, 1), 1);

for w = 1:size(windows_ms, 1)
    time_mask = times_ms >= windows_ms(w, 1) & ...
                times_ms <= windows_ms(w, 2);

    % condition x subject x channel
    values = mean(erp_uv(:, :, :, time_mask), 4, 'omitnan');
    window_values{w} = values;

    for c = 1:n_conditions
        for s = 1:n_subjects
            for ch = 1:n_channels
                subject_col(end+1, 1) = string(subjects{s}); %#ok<SAGROW>
                condition_col(end+1, 1) = string(conditions{c}); %#ok<SAGROW>
                channel_col(end+1, 1) = string(scalp_labels{ch}); %#ok<SAGROW>
                window_col(end+1, 1) = string(window_names{w}); %#ok<SAGROW>
                mean_uv_col(end+1, 1) = values(c, s, ch); %#ok<SAGROW>
            end
        end
    end
end

window_table = table( ...
    subject_col, ...
    condition_col, ...
    channel_col, ...
    window_col, ...
    mean_uv_col, ...
    'VariableNames', { ...
        'subject', ...
        'condition', ...
        'channel', ...
        'window', ...
        'mean_amplitude_uv'});

window_table_file = fullfile( ...
    table_dir, ...
    'stern_erp_window_subject_channel.tsv');

writetable(window_table, ...
    window_table_file, ...
    'FileType', 'text', ...
    'Delimiter', '\t');

fprintf('\n=== CREATING CORRECTED OZ FIGURE ===\n');

oz_idx = find(strcmpi(scalp_labels, 'OZ'), 1);
assert(~isempty(oz_idx), 'OZ was not found.');

oz_values = squeeze(erp_uv(:, :, oz_idx, :));
% condition x subject x time

grand_mean = squeeze(mean(oz_values, 2, 'omitnan'));
grand_sem = squeeze(std(oz_values, 0, 2, 'omitnan')) ./ sqrt(n_subjects);

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1250 760]);

hold on;
line_colors = lines(n_conditions);

% Draw every uncertainty band first so no band hides another condition's line.
for c = 1:n_conditions
    upper = grand_mean(c, :) + grand_sem(c, :);
    lower = grand_mean(c, :) - grand_sem(c, :);

    fill( ...
        [times_ms(:); flipud(times_ms(:))], ...
        [upper(:); flipud(lower(:))], ...
        line_colors(c, :), ...
        'FaceAlpha', 0.13, ...
        'EdgeColor', 'none', ...
        'HandleVisibility', 'off');
end

% Draw all means after every band.
for c = 1:n_conditions
    plot( ...
        times_ms, ...
        grand_mean(c, :), ...
        'LineWidth', 2.5, ...
        'Color', line_colors(c, :), ...
        'DisplayName', conditions{c});
end

xline(0, '--', 'Stimulus onset', ...
    'LabelVerticalAlignment', 'bottom', ...
    'HandleVisibility', 'off');
yline(0, ':', 'HandleVisibility', 'off');

xlim([-200 1000]);
xlabel('Time (ms)');
ylabel('Amplitude (\muV)');
title(sprintf('STERN grand-average ERP at Oz (N = %d)', n_subjects));
legend('Location', 'northeast');
grid on;
box off;
set(gca, 'FontSize', 13);

oz_figure = fullfile( ...
    figure_dir, ...
    'stern_grand_average_erp_OZ_corrected.png');

exportgraphics(fig, oz_figure, 'Resolution', 300);
close(fig);

fprintf('\n=== CREATING CONDITION TOPOGRAPHIES ===\n');

condition_topography = fullfile( ...
    figure_dir, ...
    'stern_condition_topographies.png');

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1450 1350]);

tiledlayout(size(windows_ms, 1), n_conditions, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

for w = 1:size(windows_ms, 1)
    values = window_values{w};
    grand_values = squeeze(mean(values, 2, 'omitnan'));
    % condition x channel

    row_limit = max(abs(grand_values), [], 'all');
    if row_limit == 0
        row_limit = 1;
    end

    for c = 1:n_conditions
        nexttile;

        topoplot( ...
            grand_values(c, :), ...
            chanlocs, ...
            'electrodes', 'on', ...
            'maplimits', [-row_limit row_limit], ...
            'style', 'map', ...
            'shading', 'interp');

        title(sprintf('%s — %s', conditions{c}, window_pretty{w}));
        colorbar;
    end
end

sgtitle(sprintf( ...
    'STERN ERP scalp topographies (N = %d; amplitude in \\muV)', ...
    n_subjects));

exportgraphics(fig, condition_topography, 'Resolution', 300);
close(fig);

fprintf('\n=== CREATING DIFFERENCE TOPOGRAPHIES ===\n');

contrast_names = { ...
    'Memorize - Ignore', ...
    'Probe - Memorize', ...
    'Probe - Ignore'};

contrast_pairs = [ ...
    2 1; ...
    3 2; ...
    3 1];

difference_topography = fullfile( ...
    figure_dir, ...
    'stern_difference_topographies.png');

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1450 1350]);

tiledlayout(size(windows_ms, 1), size(contrast_pairs, 1), ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

for w = 1:size(windows_ms, 1)
    values = window_values{w};
    difference_maps = nan(size(contrast_pairs, 1), n_channels);

    for k = 1:size(contrast_pairs, 1)
        a = contrast_pairs(k, 1);
        b = contrast_pairs(k, 2);

        difference_maps(k, :) = squeeze(mean( ...
            values(a, :, :) - values(b, :, :), ...
            2, ...
            'omitnan'));
    end

    row_limit = max(abs(difference_maps), [], 'all');
    if row_limit == 0
        row_limit = 1;
    end

    for k = 1:size(contrast_pairs, 1)
        nexttile;

        topoplot( ...
            difference_maps(k, :), ...
            chanlocs, ...
            'electrodes', 'on', ...
            'maplimits', [-row_limit row_limit], ...
            'style', 'map', ...
            'shading', 'interp');

        title(sprintf('%s — %s', ...
            contrast_names{k}, ...
            window_pretty{w}));

        colorbar;
    end
end

sgtitle(sprintf( ...
    'STERN paired ERP difference topographies (N = %d; amplitude in \\muV)', ...
    n_subjects));

exportgraphics(fig, difference_topography, 'Resolution', 300);
close(fig);

fprintf('\n=== WRITING QC SUMMARY ===\n');

summary_file = fullfile( ...
    summary_dir, ...
    'stern_erp_stage2_qc_summary.txt');

fid = fopen(summary_file, 'w');
assert(fid ~= -1, ...
    'Could not create summary: %s', summary_file);

fprintf(fid, '=== STERN ERP STAGE 2 QC SUMMARY ===\n');
fprintf(fid, 'EEGLAB version: %s\n', eeg_getversion);
fprintf(fid, 'MATLAB version: %s\n', version);
fprintf(fid, 'Subjects: %d\n', n_subjects);
fprintf(fid, 'Conditions: %s\n', strjoin(conditions, ', '));
fprintf(fid, 'Scalp EEG channels: %d\n', n_channels);
fprintf(fid, 'Eye channels excluded: LEYE, REYE\n');
fprintf(fid, 'Time points: %d\n', n_times);
fprintf(fid, 'Time range: %.0f to %.0f ms\n', ...
    min(times_ms), max(times_ms));
fprintf(fid, 'ERP array order: condition x subject x channel x time\n');
fprintf(fid, 'ERP array size: %s\n', mat2str(size(erp_uv)));
fprintf(fid, 'ERP NaN count: %d\n', sum(isnan(erp_uv), 'all'));
fprintf(fid, 'Windows: %s\n', strjoin(window_pretty, ', '));

for w = 1:size(windows_ms, 1)
    time_mask = times_ms >= windows_ms(w, 1) & ...
                times_ms <= windows_ms(w, 2);

    for c = 1:n_conditions
        oz_subject_values = squeeze(mean( ...
            erp_uv(c, :, oz_idx, time_mask), ...
            4, ...
            'omitnan'));

        fprintf(fid, ...
            'Oz %s %s: mean %.6f uV; SD %.6f uV\n', ...
            conditions{c}, ...
            window_pretty{w}, ...
            mean(oz_subject_values, 'omitnan'), ...
            std(oz_subject_values, 0, 'omitnan'));
    end
end

fprintf(fid, 'All-channel MAT: %s\n', mat_file);
fprintf(fid, 'Window table: %s\n', window_table_file);
fprintf(fid, 'Corrected Oz figure: %s\n', oz_figure);
fprintf(fid, 'Condition topographies: %s\n', condition_topography);
fprintf(fid, 'Difference topographies: %s\n', difference_topography);

fclose(fid);

fprintf('\n=== STERN ERP STAGE 2 QC PASSED ===\n');
fprintf('ERP_MAT=%s\n', mat_file);
fprintf('WINDOW_TABLE=%s\n', window_table_file);
fprintf('OZ_FIGURE=%s\n', oz_figure);
fprintf('CONDITION_TOPOGRAPHIES=%s\n', condition_topography);
fprintf('DIFFERENCE_TOPOGRAPHIES=%s\n', difference_topography);
fprintf('SUMMARY=%s\n', summary_file);

function normalized = normalize_erp_array( ...
    raw, ...
    n_times, ...
    n_channels, ...
    n_subjects)

    raw = squeeze(raw);
    raw_size = size(raw);

    while numel(raw_size) < 3
        raw_size(end+1) = 1;
    end

    raw = reshape(raw, raw_size(1), raw_size(2), raw_size(3));

    all_permutations = perms(1:3);

    for i = 1:size(all_permutations, 1)
        candidate = permute(raw, all_permutations(i, :));

        if isequal( ...
            size(candidate), ...
            [n_times n_channels n_subjects])
            normalized = candidate;
            return;
        end
    end

    error( ...
        ['Could not normalize ERP array. Raw size: %s; expected a ' ...
         'permutation of [%d %d %d].'], ...
        mat2str(size(raw)), ...
        n_times, ...
        n_channels, ...
        n_subjects);
end
